pycaret/pycaret

preprocess.py

Fix for https://github.com/pycaret/pycaret/issues/18
Tested on my old big dataframe from the other my pull request + tested on the data from issue above
The problem happens at the stage when highly correlated features are removed.
Correlation between 1 feature is 1, which is not the matrix, so pandas dataframe can not be created and there is no need for further correlation analysis. 
I added extra checking to see if there is only 1 feature and return original frame if there is.
Also, to save some time for very big dataframes (as drop had to be done 3 times +1 with this fix), I added 1 variable and replaced with it those 3 places. Sorry for having 2 fixes in the same place. I know it's a bad practice, but...

fix for dataframe constructor with 1 feature

---

preprocess.py

Fix for https://github.com/pycaret/pycaret/issues/19
It was caused by ID column detector.
It was creating big ranges for features that had very big numbers and then comparing such ranges with sorted features. Sometimes it results in "out of memory" problem.
Now there are no ranges. ID column is detected by increment checking. If all increments in sorted array are 1, then it's ID column.
Potential way to save more memory and power:
Use loop and compare increment by increment unless there is a difference other than 1.
It will save more memory as there will be no additional array created + when it's not ID column, loop will stop at first stages without having to calculate further increments. While now all the increments are calculated.
But I decided to keep the same "beautiful" style based …

fix memory issue for features with big numbers (ID column detection)

---

MANIFEST.in
setup.py

Before we had to change requirements in two files, now it's done only in requirements.txt, so that people who do not want to install it as package can just simply load it from git and install with requirements.txt. That's the reason we dont move everything to just setup.py
Though, you might keep it as it is now. I've never been paying attention how it's done, so I just did as it's said in https://github.com/pycaret/pycaret/pull/78

Moved setup requirements to requirements.txt only

---

.travis.yml

The purpose is to unify the rules with other command(pip)　.

Replace python3 command with python command

---

pycaret/classification.py

Adds an option to classificaiton `predict_models()` to output labels as original categories, instead of outputting them in an encoded integer form. Default behavior is unchanged.
References https://github.com/pycaret/pycaret/issues/262

Categorical labels for classification predict_models()

---

pycaret/classification.py
pycaret/regression.py

Adds functionality from https://github.com/pycaret/pycaret/pull/348 to `master`, fixes an issue where unseen data passed to `predict_model()` in classification or regression would result in misaligned indices after appending the `Label` column.

Categorical labels, fix predict indices

---

pycaret/anomaly.py

Fixes `pandas` being written as `pands` in anomaly.py docstrings.

Fix typo in docstrings

---

pycaret/classification.py

1. Makes the behavior added by https://github.com/pycaret/pycaret/pull/348 default and only.
2. Uses a cleaner way to append the Label column to unseen data.

Categorical labels by default

---

.github/CI/check_latest_commit_for_nightly.py
.github/workflows/build_publish_nightly.yml
.github/workflows/test.yml
pycaret/utils.py
setup_nightly.py

The following changes will put in place a workflow that:
- Will run every 24h on midnight zulu time
- Will check whether the latest commit on master that passed CI has been made in the last 24 hours
- If yes, will build and publish pycaret-nightly using that commit
- Otherwise, end action
Will require a PyPi token to be set as `pypi_password` secret. Instructions on how to do it are here - https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github
Several files needed to be edited in order to facilitate smooth building and publishing. The main change is that both setup.py files will get the version from pycaret/utils.py, in order to make sure it is in one place. …

Nightly publish workflow

---

pycaret/tests/test_utils.py
pycaret/utils.py

Fix `check_metric` for MAPE returning NaN.
Fixes https://github.com/pycaret/pycaret/issues/458

Fix MAPE check_metric returning NaN, enable test

---

pycaret/anomaly.py
pycaret/arules.py
pycaret/classification.py
pycaret/clustering.py
pycaret/regression.py

Add `scale` parameter to plot_model to allow for rendering of plots in higher resolution (aside from NLP, which only has interactive plots).
I chose `scale` instead of `dpi` because plotly.express doesn't allow setting of dpi and only allows for pixel values. Other plots have their dpi scaled.
Fixes https://github.com/pycaret/pycaret/issues/394

scale parameter for plot_model

---

pycaret/classification.py
pycaret/regression.py

Adds `budget_time` parameter to `compare_models()` in classification and regression. It allows the user to specify the limit on the time taken (in minutes) by the function. If the runtime of the function goes over the budget, the model fitting loop will be broken, returning only the models that have been completely fitted up to that point.
Also adds a type check for `n_select` and makes sure it can't go over the size of the fitted models list.

budget_time param for compare_models

---

pycaret/classification.py

Add encoded_labels param to predict_model so that users can get numerical labels for use in other functions.

Add encoded_labels param to predict_model

---

.github/workflows/build_publish_nightly.yml

This will make sure that the Action will not show up as failed when there was no need to update nightly build.

Github Actions, don't fail when update is not necessary

---

.github/CI/check_latest_commit_for_nightly.py

Fixes an issue where the nightly publish script would consider a workflow run for a PR of a 'master' branch from a fork.

Don't consider action results for forks

---

pycaret/anomaly.py
pycaret/classification.py
pycaret/clustering.py
pycaret/regression.py

This PR adds a warning to alert when `predict_model` is attempting to consume a model built with a different version of Pycaret than the one used to instantiate predict_model. 
Related issue [here](https://github.com/pycaret/pycaret/issues/593).

Adding a warning to all modules predict_model docstring

---

MANIFEST.in

pycaret cannot build on conda-forge without this file in the manifest
See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=237520&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=460

Add requirements-optional.txt

---

pycaret/internal/preprocess.py
pycaret/tests/test_preprocess.py

- Add imputation strategy for time columns for simple imputer.
- Refactor and restructure the code for time columns with sklearn's simple imputer.
- Fixed the exception that happens when categorical strategy is not passed in correctly.

Added imputation strategy for time columns for simple imputer

---

pycaret/anomaly.py
pycaret/arules.py
pycaret/classification.py
pycaret/clustering.py
pycaret/internal/tabular.py
pycaret/nlp.py
pycaret/regression.py

Added `display_format`
```
def plot_model(model, plot="2d", scale=1, display_format=None):
.
.
.
if display_format=='streamlit'
st.write(fig)
else:
fig.show()
```
* Didn't include `import streamlit as st` since this will only work inside streamlit anyway
* Didn't use [`st.plotly_chart`](https://docs.streamlit.io/en/stable/api.html#streamlit.plotly_chart) since [`st.write`](https://docs.streamlit.io/en/stable/api.html#streamlit.write) can plot many types of charts and won't have to be changed if plotly is dropped later
* Added `display_format` to anywhere `plot_model` can be called 😃
* Error handling
In [nlp.py](https://github.com/pycaret/pycaret/blob/plot-in-streamlit/pycaret/nlp.py) where `fig.iplot()` is used, I had to change [`asFigure = …

display association rules plots in streamlit

---

pycaret/internal/PycaretExperiment.py

Fixed the cutoff of long text in png graphs in PycaretExperiment.py

Fixed the cutoff of long text in png graphs

---

pycaret/arules.py

Added low_memory and max_len support to arules.py for large datasets or low resource compute spaces.
apriori.apriori already has support for low_memory and max_len so just adding this option to arules.py

Added low_memory and max_len support to arules.py

---

pycaret/datasets.py

- https://github.com/pycaret/pycaret/issues/1038
- Added initial dateset structure for Time Series.
Currently testing on local notebook. Will add unit tests later.
ImportError is loading an sktime dataset and sktime is not installed.

added initial dataset per https://github.com/pycaret/pycaret/issues/1038

---

pycaret/containers/metrics/time_series.py
pycaret/tests/test_utils.py
pycaret/utils.py
requirements-optional.txt

* [#1039]
Major changes of this branch include:
* Add SMAPE, MAPE, MASE, MAE and RMSE containers for time series. [link](https://github.com/pycaret/pycaret/blob/time_series_metrics/pycaret/containers/metrics/time_series.py#L153)
Minor changes include:
* Add `sktime` as a requirement to `requirements-optional` to ensure installation during CI stage. [link](https://github.com/pycaret/pycaret/blob/time_series_metrics/requirements-optional.txt#L11)
Testing changes include:
* Added time series metrics testing to `check_metric` function. [link](https://github.com/pycaret/pycaret/blob/time_series_metrics/pycaret/utils.py#L64)
*  Test float values through `numpy.testing.assert_almost_equal`. [example](https://github.com/pycaret/pycaret/blob/time_series_ …

Time series metrics

---

pycaret/internal/persistence.py

- AWS deployed models can't be loaded
Fixes: #1127 
load_model() for AWS deployed model was calling 'filename' instead of 'model_name'.
Model could not load because it was appending .pkl twice.
Sorry, this is my first PR for pycaret so unsure of the guidelines!
Reran the demo code with the change from my fork of pycaret and it works.
NA
NA

Fix load_model() for AWS models in persistence.py

---

pycaret/internal/PycaretExperiment.py
pycaret/internal/utils.py
pycaret/tests/test_time_series.py
pycaret/tests/test_time_series_splitters.py
pycaret/time_series.py

Major changes are:
* User can set a seasonal parameter `sp` in the setup function, if not provided the frequency of the PeriodIndex will be taken as the seasonal parameter. [link](https://github.com/pycaret/pycaret/blob/time_series_seasonal_parameter/pycaret/time_series.py#L125)
* The forecast horizon `fh` splits the original data in train/test, before this change the `train_size` parameter splitted the original data. [link](https://github.com/pycaret/pycaret/blob/time_series_seasonal_parameter/pycaret/internal/PycaretExperiment.py#L4712)
No new tests added, however two test are modified:
*  `test_create_model` and `test_tune_model`  to assert that the prediction index match the last `fh` elements of the original data. …

Time series seasonal parameter and fh splitting data.

---

pycaret/containers/metrics/time_series.py
pycaret/internal/utils.py
pycaret/tests/test_time_series.py

There were circular imports when ModelContainer and MetricsContainer were imported in the same file. Fixed this.
Also, cleaned up some unit tests for time_series
Unit Tests are passing.

Fixes circular imports

---

pycaret/classification.py
pycaret/internal/tabular.py
pycaret/regression.py
pycaret/tests/test_classification_plots.py
pycaret/tests/test_regression_plots.py

- Previously, `pycaret.internal.tabular.interpret_model` only worked for observations within the training/test data.
- This PR adds an option `X_new_sample: Optional[pd.DataFrame] = None` which allows the user to use other data that is in the exact same format as the original dataset. 
Fixes: #254 
In order to use outside data, the new data is simply transformed by the `prep_pipe` from global scope via `test_X = prep_pipe.transform(X_new_sample)`.
- [x ] New feature (non-breaking change which adds functionality)
- [x ] This change requires a documentation update
Tests plots are generated in `pycaret/tests/test_classification_plots.py` and `pycaret/tests/test_regression_plots.py` which use the first ten rows of the dataset. The plots are generated without error.

add X_new_sample option to interpret_model

---

pycaret/containers/models/time_series.py
pycaret/internal/pycaret_experiment/supervised_experiment.py
pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/internal/tabular.py

Alternate, simpler approach to sklearn models for time series.

Alternative approach to TS scikit models

---

pycaret/regression.py

I believe there is a typo at "RVF" Kernel. I changed it to RBF to make it clear :)

Fix Typo from RVF to RBF

---

pycaret/anomaly.py
pycaret/classification.py
pycaret/clustering.py
pycaret/internal/preprocess.py
pycaret/regression.py

`remove_multicollinearity` was considering all columns instead of just numerical ones, leading to exceptions in certain cases.
`remove_multicollinearity` now only considers numerical columns. Docstrings have been updated.

Fix remove_multicollinearity considering cat feats

---

pycaret/internal/pycaret_experiment/tabular_experiment.py
pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/tests/test_time_series_splitters.py

Previously, time series experiment only accepted a string as input for fold_strategy. With this change, it can also accept a sktime compatible cv object directly. If an object is passed, then the `fold` and `fh` parameters in setup are ignored and are extracted from the cv object directly.
Updated unit tests
None

Fold Strategy Updates

---

pycaret/internal/tabular.py

- #1312 
Fixes: #[issue number that will be closed through this PR] #1312
Currently, when the target variable is binary the 'summary' plot from the interpret_model shows a bar as opposed to beeswarm.

fixed shap summary plot bug for binary classification models

---

.gitignore
pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/tests/test_time_series.py
pycaret/time_series.py

Cleaned up finalize_model and added unit tests
Unit tests have been updated

finalize_model

---

pycaret/internal/tabular.py

Addresses Issue #1131
- This PR addresses Issue 1131, which noted that the display for the `setup()` function did not display the `remove_perfect_collinearity` argument.
Fixes: #1131
Simply added a new list
```
["Remove Perfect Collinearity", remove_perfect_collinearity]
```
to the the `functions` DataFrame being passed to Display.
Note that I've checked the checkboxes about documentation and downstream changes below, since I'm just addressing a minor omission/bug and this has no implication for documentation or downstream modules.
I ran the `setup` function on a local machine to check if the display was, indeed, showing the new "Remove Perfect Collinearity" option and it was.
NA
:--------------------: …

Added remove_perfect_collinearity to setup display

---

pycaret/internal/pycaret_experiment/supervised_experiment.py
pycaret/internal/pycaret_experiment/tabular_experiment.py
pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/tests/test_time_series.py
pycaret/time_series.py

Unit tests have been added and pass locally.

Support for custom folds

---

pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/tests/test_time_series.py

Time Series tune_model does not work with non-default `optimize` argument
```python
tune_model(model, optimize = 'MAE')
```  
```bash
~\pycaret-timeseries\pycaret\pycaret\time_series.py in fit(self, y, X, **fit_params)
2199             raise ValueError(
2200                 f"Refit Metric: '{refit_metric}' is not available. ",
-> 2201                 f"Available Values are: {list(scorers.keys())}",
2202             )
2203 
ValueError: ("Refit Metric: 'smape' is not available. ", "Available Values are: ['MAE']")
```
Fixed the above mentioned issue. Refit metric was not being passed to the Grid Search instantiation earlier.

fix for non default optimize metric

---

pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/tests/test_time_series.py

* predict_model displays the test metrics now when verbose is set to True (default)
* Note that this is slightly different from the regression.classification case. There are several corner cases such as: 
- If the model has not been finalized, prediction match y_test
- If the model has been finalized, predictions will not match the indices from y_test (metrics display NaN in that case)
- Also, the user can use a different fh length in predict compared to what was used in setup. In this case, only the common indices in prediction and test are used to compute the metrics.
Warnings are issued for all corner cases identified above

added display for test metrics in predict model

---

pycaret/containers/models/time_series.py
pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/time_series.py

During create_model calls, only folds were displayed earlier (similar to regression/classification). But in time series, since the temporal dependency is maintained in the folds, it is useful to also add the cutoff for the training data to know exactly what was used for training each fold (all values on or before the cutoff are used for training). This has now been added.
Existing unit tests pass

Added cutoffs to score dataframe

---

pycaret/internal/pycaret_experiment/supervised_experiment.py
pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/tests/test_time_series.py
pycaret/time_series.py

1. After adding `get_fold_generator` functionality for time series, `compare_models` is breaking (not returning any models). This was not caught in CI since the test for compare_models was missing.
2. Also fixed functional API for `blend_models` which was failing earlier due to incorrect default metric.
Fixed the issue mentioned above and added unit test for `compare_models`.

fix for compare_model folds

---

pycaret/containers/models/classification.py
pycaret/containers/models/regression.py
pycaret/internal/tabular.py

This PR adds support for CUDA version of LightGBM.
At present, PyCaret only supports OpenCL version of LightGBM( as introduced in `PyCaret on GPU` of `README.md`.
Actually, LightGBM also supports a (experimental) CUDA version(https://github.com/microsoft/LightGBM/tree/master/python-package). To use CUDA version, we only need to set `device="cuda"` in `LGBMRegressor` / `LGBMClassifier`.
I made some changes in `containers/models/classification.py`/`containers/models/regression.py` to make LightGBM works properly with `gpu_param=True` or  `gpu_param="force"` , when CUDA version( instead of OpenCL version) of LightGBM is installed.
PS: 
- To build CUDA version: `pip install lightgbm --install-option=--cuda`
- I don't know if information related to LightGBM on GPU should be changed in …

Add support for CUDA version of LightGBM

---

pycaret/containers/metrics/time_series.py
pycaret/containers/models/time_series.py
requirements-ts.txt

- Initial changes fir upgrade to sktime 0.7.0. 
- Fixed updated for metrics and BaseForecaster
- Now errors out at the Splitters
```python
Traceback (most recent call last):
File "c:/Users/Nikhil/OneDrive/my_libraries/my_python_libraries/pycaret_dev/time_series_debug.py", line 41, in <module>
exp.setup(data=y, fh=fh, fold=fold, fold_strategy="expanding", session_id=42, n_jobs=-1)
File "c:\Users\Nikhil\OneDrive\my_libraries\my_python_libraries\pycaret_dev\pycaret\internal\pycaret_experiment\time_series_experiment.py", line 1062, in setup
profile_kwargs=profile_kwargs,
File "c:\Users\Nikhil\OneDrive\my_libraries\my_python_libraries\pycaret_dev\pycaret\internal\pycaret_experiment\tabular_experiment.py", line 1570, in setup
self.fold_generator = self.get_fold_generator(fold=self.fold_param) …
```

initial changes until splitters

---

pycaret/containers/models/time_series.py
pycaret/internal/ensemble.py
pycaret/internal/pycaret_experiment/tabular_experiment.py
pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/tests/test_preprocess.py
pycaret/tests/test_time_series.py
pycaret/tests/test_time_series_splitters.py

Fixes: https://github.com/pycaret/pycaret/issues/1369
Old unit tests are passing as expected (except blend tests which have been disabled for now)

more updates to make sktime 0.7.0 compatible. Disabled ensemble/blend for now

---

pycaret/containers/metrics/time_series.py
pycaret/internal/pycaret_experiment/time_series_experiment.py

Fixes the `_fit_and_score` method in time series not passing metric kwargs to function calls, leading to inaccurate metric values.

[timeseries] Fix`_fit_and_score` metrics not getting their kwargs

---

pycaret/internal/tabular.py

Fixed `compare_models` not being able to handle a situation where all 0.0s are returned in train-test split. This is a follow up to https://github.com/pycaret/pycaret/pull/1510.

Fix `compare_models` errors="ignore" not handling 0.0

---

pycaret/internal/pipeline.py
pycaret/internal/validation.py

Instead of carrying over fit attributes of the final estimator in a pipeline, we simply use `__getattr__` to redirect the calls there, greatly simplifying and futureproofing the code.

Use `__getattr__` in pipeline for fit vars

---

pycaret/classification.py
pycaret/internal/tabular.py
pycaret/regression.py

I have recently implemented a new function called `get_leaderboard`. This function retrieves all the trained model object and their metrics from global variables and returns as `pandas.DataFrame`. This is how the desired output looks like:
I created this function in my Notebook and used the `get_config` function to retrieve everything I needed. Here is my code:
```
import pandas as pd
from pycaret.internal.tabular import _get_model_name
def get_leaderboard():
model_container = get_config('master_model_container')
result_container = get_config('create_model_container')
result_container_mean = []
mc = 0
for i in np.arange(0,len(result_container)):
c = result_container[i]
r = c[-2:-1]
model_name = _get_model_name(model_container[mc]) 
r['Model Name'] = model_name
r['Model'] = …
```

get_leaderboard

---

pycaret/internal/plots/yellowbrick.py
pycaret/internal/tabular.py
pycaret/nlp.py

- Enhanced the plot_model function to save the figure at any destination in the system. 
Modified the save argument of plot_model to save the figure at the destination mentioned by the user. Instead of just saving the figure in the current directory.
Tested with the confusion matrix plot.
NA
Original picture of Log file         | Picture saved at the destination mentioned
**![Screenshot (422)_LI](https://user-images.githubusercontent.com/44323155/131104602-d19bfb6d-3bd2-40de-8c0f-bdcbd2ba6ec4.jpg)**  | <b>
</b> |

Modified save argument of plot_model()

---

pycaret/internal/tabular.py

- Bug 1581
- https://github.com/pycaret/pycaret/issues/1581
Added plt.close() after any use of the function interpret_model() when the parameter save is set up as True.
```
import os
import pycaret.classification as clf
data = get_data('blood')
s = clf.setup(data, train_size=0.80, target='Class', session_id=42, silent=True)
rf = clf.create_model('rf', verbose=False)
clf.tune_model(rf, optimize='auc', n_iter=10, fold=5)
clf.plot_model(rf, plot='auc', verbose=False, save=True)
os.rename('AUC.png', 'AUC_before_interpret.png')
clf.plot_model(rf, plot='confusion_matrix', verbose=False, save=True)
os.rename('Confusion Matrix.png', 'Confusion …
```

Closing plt module after saving figure on interpret_model function.

---

pycaret/internal/preprocess.py
pycaret/tests/test_regression.py

Fixes: #1609 
Fixed the issue where Fix_multicollinearity does not work when target is float32 or float64.
- [ x] Bug fix (non-breaking change which fixes an issue)
Reproduced the issue by adding the multicollinearity setting in test_regression.py. The test is passed with the new code.
NA

fix the issue in Fix_multicollinearity when target is float32 or float64

---

pycaret/internal/plots/time_series.py
pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/time_series.py

- #1699
- Added return_fig argument to plot_model()
- plot_model reverted to previous functionality of showing fig internally by default. 
Unit tests run locally
- x ] My code follows the style guidelines of this project.

fix for no fig.show and added return_fig arg per #1699

---

pycaret/classification.py
pycaret/internal/tabular.py
pycaret/regression.py

Closes https://github.com/pycaret/pycaret/issues/1676
Closes https://github.com/pycaret/pycaret/issues/1384
The internal CV conducted inside sklearn stacking estimators should be independent of the outside CV.

Separate argument for stacking CV

---

pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/tests/test_time_series.py

Related to #1836
`predict_model` with prediction interval now returns an extra column that indicates whether the point estimate is within prediction interval or not.

added column for point estimate within pi (outlier or not) in support of #1836

---

pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/tests/test_time_series.py

Reverts pycaret/pycaret#1863
This is not correct. The check has to be made with actual data not predictions. Hence reverting back.

Revert "added column for point estimate within pi (outlier or not) in support of #1836"

---

pycaret/containers/metrics/time_series.py
pycaret/internal/pycaret_experiment/supervised_experiment.py
pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/internal/utils.py
pycaret/tests/test_time_series.py
pycaret/tests/test_time_series_metrics.py
pycaret/time_series.py

Closes https://github.com/pycaret/pycaret/issues/1331
Closes #1406 
- Added option to pass additional kwargs to scorers (some of them like `sp` come from experiment, others like `y_train`, `lower` and `upper`  prediction limit from from respective folds in `fit_and_score`. These are needed for metrics like MASE, INPI, etc.
Unit test have been added and existing ones pass

Add support for metrics with custom arguments like MASE, INPI

---

pycaret/internal/tabular.py

Info about Issue or bug 
Closes #1981
The `fit_transform` method of the `DataTypes_Auto_infer` class is a method that encodes and transforms the target into numeric data (0, 1, ..., N) when the target is the label of an object, and if such data has already been passed, the `replacement` attribute is not be made.
https://github.com/pycaret/pycaret/blob/8b3e4f26225667a801cdd2de94d1010730fe10e6/pycaret/internal/preprocess.py#L432
Therefore, an `AttributeError` occurs at L7050 in `table.py`.
https://github.com/pycaret/pycaret/blob/8b3e4f26225667a801cdd2de94d1010730fe10e6/pycaret/internal/tabular.py#L7050
Incidentally, this error also occurs when the objective variable is "object", because "object" is converted to "int64" in L421. 
https://github.com/pycaret/pycaret/blob/8b3e4f26225667a801cdd2d …

[BUG] Fix class_names for plot_tree

---

pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/tests/test_time_series_plots.py

#2029 
Closes #2029
- Modularization of unit tests for `return_data` argument in `plot_model`
- Also fixed bug with plotting when the plot is not possible (e.g. decomp with RangeIndex). Earlier, it gave a print error message but also an error that stopped execution. This error is resolved now.
Unit tests have been added and updated. Pass locally

made unit tests more modular per #2029

---

pycaret/classification.py
pycaret/internal/tabular.py
pycaret/tests/test_optimize_threshold.py

Completely revamped `optimize_threshold` function. Only impact `pycaret.classification` module.
Prior to this revamp, the `optimize_threshold` function uses metrics on the hold-out set to determine the best metric. 
It also required `true_positive`, `false_positive`, `true_negative`, and `false_negative` to be entered as a parameter to the `optimize_threshold` function.
This revamp makes use of the `probability_threshold` parameter in the `create_model` (added in 2.3.5) and also uses the metrics from the metric container as opposed to asking the user to define tp,fp,tn,fn. It also works with custom metrics added to pycaret through the `add_metric` function.
Finally, previously we were only returning the float (Example: 0.66) at which point the custom cost function is optimized. Now we are …

revamped optimize_threshold function in classification module

---

pycaret/internal/pycaret_experiment/tabular_experiment.py

Fix for #1914
`COV_PROB` was being displayed as a metric even when `enforce_pi = False`. Added fix so this is only displayed when `enforce_pi = True`
Existing unit tests pass

fix for COV_PROB metric

---

pycaret/internal/pycaret_experiment/time_series_experiment.py

Minor bug in exogenous handling in `_fit_and_predict`. Needed to change from loc to iloc since train and test indices returned by cv splitter are integer based.
Unit tests to be rerun on GitHub

Time Series changed X to integer based indexing in _fit_and_score

---

.github/workflows/test.yml
requirements-ts.txt

The new version of sktime 0.10.0 broke the pycaret release. Fixed the version so that it only takes 0.9.x for now.

Fix for breaking release

---

.gitignore
pycaret/internal/plots/time_series.py
pycaret/internal/plots/utils/time_series.py
pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/time_series.py
time_series_203.ipynb

#2149
Plotting unit tests ran locally and passed.

Making rendering of plots faster

---

pycaret/internal/tabular.py

At the moment `create_api` function uses all the columns from the original dataset minus the target column. However, API should also ignore the ID column and any feature that is explicitly passed in the `ignore_features` parameter as they are not used for training.
I have added two lines of code in `tabular.py` under the `create_app` function that does that:
```
cols_to_drop = [*get_config("prep_pipe")[0].features_todrop] + get_config("prep_pipe")[0].id_columns
removed_cols = [input_cols.remove(i) for i in cols_to_drop]`
```
Example:
```
data = get_data('iris')
s = setup(data, target = 'species', session_id = 123, ignore_features = ['petal_width'])
lr = create_model('lr')
create_api(lr, 'my_lr_api')
```
**Notice …

update create_api function

---

pycaret/containers/models/time_series.py
pycaret/internal/pycaret_experiment/time_series_experiment.py
pycaret/tests/conftest.py
pycaret/tests/test_time_series_exogenous.py
pycaret/tests/test_time_series_setup.py
pycaret/tests/time_series_test_utils.py
pycaret/time_series.py
pycaret/utils/time_series/__init__.py
pycaret/utils/time_series/forecasting/models.py

Closes #2133 
- Added an argument to setup called `enforce_exogenous`. If True and the data has exogenous variables, then only models that support exogenous variables are enabled.
Unit tests have been added

Provide option to enforce models that support exogenous variables only

---

pycaret/classification.py
pycaret/internal/drift_report.py
pycaret/internal/tabular.py
pycaret/regression.py

Patch for #2150. It works with the below snippet:
``` python
data = get_data('juice')
un_seen=data[1000:]
data=data[:1000]
exp_name = setup(data = data,  target = 'Purchase', verbose=False, silent=True)
dt = create_model('lightgbm')
preds = predict_model(dt, data=un_seen,drift_report = True, drift_kwargs = {'reference' : data})
```

drift_report for new data

---

pycaret/internal/plots/time_series.py
pycaret/tests/test_time_series_base.py
pycaret/tests/test_time_series_exogenous.py
pycaret/tests/test_time_series_tune_base.py
pycaret/tests/test_time_series_tune_grid.py
pycaret/tests/test_time_series_tune_random.py
pycaret/time_series/forecasting/oop.py
pycaret/utils/time_series/forecasting/__init__.py

Closes #1616 
- Added support for multiple estimators in "forecast" and "insample" plots.
- If estimator does not support insample predictions, it is simply ignored.
- If the user provides multiple models for plots that do not support it, the first one is used.
Local testing.

added support for multiple model forecasts per #1616

---

pycaret/internal/plots/time_series.py

Implemented #[2343](https://github.com/pycaret/pycaret/issues/2343)
Updated plot_acf and plot_pacf to reuse the corr_subplot component instead of replicating the code to create these plots again.
Tested locally with `pytest`
NA

Updated ACF and PACF plots to reuse subplot logic directly

---

pycaret/time_series/forecasting/oop.py

Fixes #[2338](https://github.com/pycaret/pycaret/issues/2338)
Added warning for not running setup before other functions. 
Pytest
NA

Added warning for not running setup before other functions

---

pycaret/classification.py
pycaret/regression.py

Closes #2322
Add `dict` out of `locals()` to prevent the following local variable to inject into the parameters:
```python
_pycaret_setup_call = dict(func=setup, params=dict(locals()))
```
I couldn't reproduce the issue on Databricks as reported in https://github.com/pycaret/pycaret/issues/2322
But this is the place that can potentially cause issues. So let's fix this and test on Databricks again.
NA

Fix potential parameter leaking for ParallelBackend

---

pycaret/time_series/forecasting/oop.py
pycaret/utils/time_series/forecasting/pipeline.py

Closes #2337 
sktime 0.11.0 and below do not support prediction intervals in pipelines. This PR is a fix for this when the pipeline is empty. In this case, the underlying model is used directly for predictions so that we can get the intervals.
This is a temporary fix until the pipelines can support prediction intervals. Once that is done, we can remove this.
Unit tests to be run on GH

Fix for prediction intervals with pipelines

---

pycaret/internal/preprocess/time_series/forecasting/preprocessor.py
pycaret/internal/pycaret_experiment/supervised_experiment.py
pycaret/internal/pycaret_experiment/tabular_experiment.py
pycaret/tests/conftest.py
pycaret/tests/test_pipeline.py
pycaret/tests/test_time_series_blending.py
pycaret/tests/test_time_series_metrics.py
pycaret/tests/test_time_series_models.py
pycaret/tests/test_time_series_preprocess.py
pycaret/tests/test_time_series_utils_pipeline.py
pycaret/time_series/forecasting/oop.py
pycaret/utils/time_series/forecasting/model_selection.py
pycaret/utils/time_series/forecasting/pipeline.py

Closes #2369 
Closes #2400 
- Metric calculation now uses the imputed data on the entire dataset as ground truth value.
- Fixed `tune_model` to make it work with pipeline
- Fix for finalized model having wrong memory in the `PyCaretForecastingPipeline`, but correct one in the internal model.
- Cleaned up documentation
- Added checks in code to avoid unexpected conditions
- Added many tests including some for critical pipeline functions.
- Updated docstring to make data type clear with examples
- New unit tests have been added.
- Existing checks run locally

Time Series - Metrics with missing data

---

pycaret/internal/plots/time_series.py
pycaret/internal/plots/utils/time_series.py
pycaret/internal/pycaret_experiment/pycaret_experiment.py
pycaret/tests/test_time_series_plots.py
pycaret/tests/test_time_series_preprocess.py
pycaret/tests/test_time_series_utils_plots.py
pycaret/time_series/forecasting/oop.py

- Partially Implements #2364
- Also fixed a bug in the retrieval of test values
- Added ability for `ts` and `train_test_split` plots to accept different plot data types - "original", "imputed", "transformed"
- Also fixed a bug in the retrieval of test values - these should be computed by passing the entire dataset through the pipeline and then retrieving the transformed test set values instead of just the test set through the pipeline (since we can use all past data but no future data)dataset values
Unit tests have been added for plotting as well as pipeline

Missing Data plot fixes

---

pycaret/anomaly/oop.py
pycaret/classification/oop.py
pycaret/clustering/oop.py
pycaret/internal/pycaret_experiment/pycaret_experiment.py
pycaret/internal/pycaret_experiment/supervised_experiment.py
pycaret/internal/pycaret_experiment/tabular_experiment.py
pycaret/internal/pycaret_experiment/unsupervised_experiment.py
pycaret/internal/utils.py
pycaret/regression/oop.py

Implements #2423 
According to the issue, I've refactored this line of code:
```python
from pycaret.internal.validation import *
```
... To instead use only necessary functions in where it's present, a total of 9 files. One file, ```clustering/oop.py```, didn't use anything from the reference.
Additionally, some of the code was reformatted automatically. I looked over it, and it shouldn't be an issue.
Unit tests tested locally using pytest.

Refactor import * reference to only import necessary functions #2423

---

pycaret/classification/oop.py
pycaret/clustering/oop.py
pycaret/containers/models/anomaly.py
pycaret/containers/models/classification.py
pycaret/containers/models/clustering.py
pycaret/containers/models/regression.py
pycaret/internal/pycaret_experiment/supervised_experiment.py
pycaret/internal/pycaret_experiment/unsupervised_experiment.py

Implements #2434 
According to the issue, I've refactored this line of code:
```python
from pycaret.internal.distributions import *
```
... To instead use only necessary functions in where it's present, a total of 8 files. 
- One file, ```clustering/oop.py```, didn't use anything from the reference.
- One file, ```models/regression.py```, had a duplicate of the reference.
Additionally, there was some very minor automatic code reformatting. I looked over it, and it shouldn't be an issue.
Unit tests tested locally using pytest.

Refactor import * reference to only import explicit functions #2434

---

pycaret/internal/tests/stats.py
pycaret/internal/tests/time_series.py
pycaret/tests/test_time_series_preprocess.py
pycaret/tests/test_time_series_stats.py
pycaret/tests/time_series_test_utils.py
pycaret/time_series/forecasting/functional.py
pycaret/time_series/forecasting/oop.py
pycaret/utils/time_series/exceptions.py

Closes #2427 
Closes #2430 
Closes #2431 
- Added option to run the statistical tests on various data types - "original", "imputed", "transformed"
- Appropriate error handling for missing data when running tests
- Added unit tests for missing data when running tests
- Enhanced Setup Display for preprocessing options
- Removed redundant `preprocess` argument form setup
Unit tests have been added and existing ones modified for new default (previously worked on "original" data; now works on "transformed" data by default)

changes to `check_stats`, `setup` display & arguments

---

pycaret/internal/preprocess/time_series/forecasting/preprocessor.py
pycaret/internal/pycaret_experiment/pycaret_experiment.py
pycaret/tests/test_time_series_base.py
pycaret/tests/test_time_series_preprocess.py
pycaret/tests/test_time_series_tune_base.py
pycaret/tests/test_time_series_utils_forecasting_pipeline.py
pycaret/time_series/forecasting/oop.py
pycaret/utils/time_series/forecasting/model_selection.py
pycaret/utils/time_series/forecasting/pipeline.py

Closes #2449 
Previously, (`sktime` 0.10.x), the sktime `ForecastingPipeline` did not have a transform method, so we had to add this as a `PyCaretForecastingPipeline` and maintain inside PyCaret.
But with `sktime` 0.11.0, they do have transformation capability. This PR updates the pycaret time series pipeline accordingly to use sktime constructs only without having to maintain a parallel `PyCaretForecastingPipeline` in pycaret. This makes use of the `TransformerPipeline` available in `sktime` 0.11.x.
A couple of new unit tests were added + existing unit tests should pass.

Updated pipeline to use sktime directly

---

README.md
pycaret/internal/persistence.py

The message `Transformation Pipeline and Model Successfully Loaded` will appear before loading the model.
The message is displayed after the model is loaded.
Do [the Crassification section of the quickstart](https://pycaret.gitbook.io/docs/get-started/quickstart)
NA

Corrected output timing of model successfully loaded messages

---

examples/PyCaret 2 Anomaly Detection.ipynb
pycaret/anomaly/functional.py
pycaret/classification/functional.py
pycaret/classification/oop.py
pycaret/clustering/functional.py
pycaret/internal/preprocess/preprocessor.py
pycaret/internal/preprocess/transformers.py
pycaret/internal/pycaret_experiment/supervised_experiment.py
pycaret/internal/pycaret_experiment/tabular_experiment.py
pycaret/internal/pycaret_experiment/unsupervised_experiment.py
pycaret/regression/functional.py
pycaret/regression/oop.py
pycaret/tests/test_preprocess.py
pycaret/tests/test_utils.py
pycaret/utils/constants.py
resources/Time Series 101 — For beginners.md

Closes #2790 and #2784
* It's now possible to choose which datetime columns to extract from `date_features` using parameter `create_date_columns` in setup.
* In `predict_model`, the Label and Score column names have been replaced with `prediction_label` and `prediction_score`.

Add `create_date_columns`, replace column names in `predict_model`

---

pycaret/internal/pipeline.py

Closes https://github.com/pycaret/pycaret/issues/2016
PyCaret 2.x uses sklearn 0.23.2, and PyCaret 3.x will always use the latest version of sklearn.
Since the versions of the various ML libraries are no longer fixed, this PR will embed the ML library versions (including sklearn) in the pickle file.
This PR was created with reference to [sklearn/base.py](https://github.com/scikit-learn/scikit-learn/blob/8175cd60e3df606905aedf2dd3ba0832e50cd963/sklearn/base.py#L326) :)
Here is an example.
```sh
$ python3
>>> from pycaret.datasets import get_data
>>> data = get_data('diabetes')
>>> from pycaret.classification import *
>>> s = setup(data, target = 'Class variable')
>>> best = compare_models()
>>> save_model(best, 'my_best_pipeline')
>>> 
>>> loaded_model = load_model('my_best_pipeline') …
```

Add ML library versions to pickle file for compatibility

---

pycaret/internal/pycaret_experiment/pycaret_experiment.py
pycaret/tests/test_time_series_setup.py
pycaret/time_series/forecasting/oop.py
pycaret/utils/time_series/forecasting/model_selection.py

Closes #2480
Made changes to the handling of test indices for exogenous variables (expand test indices for exogenous variables to include all points without gaps). y_test indices remain the same (with gaps).
- New tests added for FH with gaps and to test the attributes like X_test, y_test, etc. 
- Existing tests pass on GitHub

Fix for time series forecast horizon with gaps and exogenous variables

---

pycaret/anomaly/functional.py
pycaret/classification/functional.py
pycaret/classification/oop.py
pycaret/clustering/functional.py
pycaret/internal/preprocess/preprocessor.py
pycaret/internal/preprocess/transformers.py
pycaret/internal/pycaret_experiment/supervised_experiment.py
pycaret/internal/pycaret_experiment/unsupervised_experiment.py
pycaret/internal/utils.py
pycaret/regression/functional.py
pycaret/regression/oop.py
pycaret/tests/test_preprocess.py
pycaret/utils/constants.py
requirements.txt

Closes #2815
Support custom indices for the dataset. The user can now specify the `index` parameter in `setup` to specify the indices for his dataset. If specified, the indices are not reset.
Additionally, the `fix_imbalance_method` parameter now also accepts any of the imblearn estimators as string.

added index handling

---

pycaret/internal/persistence.py
pycaret/internal/pycaret_experiment/supervised_experiment.py

Closes #2769
Running `deepcopy(pipeline)` on a pipleine containing a catboost model returns the catboost estimator instead of the pipeline self. Very weird. I changed deepcopy for copy, which is fine since the underlying estimators are only used for transform

fix error catb

---

pycaret/containers/models/time_series.py

Closes #2857
Temporary fix for `use_gpu` param
Needs more work to make it work for GPUs
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

fix for `use_gpu`

---

requirements.txt

A forecasting pipeline that contains an imputer and a forecaster that does not accept missing values fails to work in the latest release of sktime (0.13.4). This used to work fine in 0.13.2 release.
Pinned sktime to 0.13.2 until bug with 0.13.4 is fixed. See: https://github.com/sktime/sktime/issues/3547
Unit tests to pass on GitHub

Time Series test fix

---

pycaret/anomaly/functional.py
pycaret/classification/functional.py
pycaret/classification/oop.py
pycaret/clustering/functional.py
pycaret/internal/preprocess/preprocessor.py
pycaret/internal/pycaret_experiment/unsupervised_experiment.py
pycaret/regression/functional.py
pycaret/regression/oop.py

Closes #3033
When someone specifies a non-numerical feature as categorical `setup` fails. Changing the default value for categorical imputation to `mode` (`most_frequent`) solves this issue and makes more sense.

cat imputation default to mode

---

pycaret/anomaly/functional.py
pycaret/classification/functional.py
pycaret/classification/oop.py
pycaret/clustering/functional.py
pycaret/internal/preprocess/preprocessor.py
pycaret/internal/pycaret_experiment/unsupervised_experiment.py
pycaret/nlp/__init__.py
pycaret/regression/functional.py
pycaret/regression/oop.py
tests/test_preprocess.py

Closes #3040
Closes #3048
* Preprocessing doesn't default to apply low_variance_threshold. We should refrain from forcing preprocessing steps as default unless strictly necessary for the models to be able to run (such as imputation)
* Fixed a bug where train and test splits weren't of the correct size
* Fixed an import issue

fix import and train test split bugs

---

pycaret/containers/models/time_series.py
pycaret/internal/preprocess/time_series/forecasting/preprocessor.py
pycaret/internal/pycaret_experiment/pycaret_experiment.py
pycaret/time_series/forecasting/functional.py
pycaret/time_series/forecasting/oop.py
pycaret/utils/time_series/forecasting/__init__.py
tests/conftest.py
tests/test_time_series_feat_eng.py
tests/time_series_test_utils.py

- Follow up to https://github.com/pycaret/pycaret/pull/3109
- (Closes #2324) Allows the user the ability to perform custom feature engineering for exogenous and target variables . Includes the ability to
- add custom lags for the targets variable
- add custom lags, windows, and summary functions for the exogenous variables. 
- add separate feature engineering for different features  
- extract Date Time Exogenous features even when data does not have exogenous variables.
- Also expands the scope of some exogenous tests to include a statistical and a reduced regression model.
- Minor spell checks
- Made docstring consistent between OOP and Functional for time series
Described above. Tests (and docstring) show how to use this feature.
Unit tests have been added.

Custom feature engineering in time series

---

pycaret/containers/models/time_series.py
pycaret/time_series/forecasting/functional.py
pycaret/time_series/forecasting/oop.py
tests/test_time_series_feat_eng.py

Closes #3118
- Fixes order of time series pipeline per #3118
- Renames the argument used to create features for target in reduced regression models from `fe_target` to `fe_target_rr` (more explicit). This will allow us to add `fe_target` argument later if we want these features to apply to all types of models.
Unit tests to pass on GH

Fix for time series pipeline order and renamed argument

---

requirements-optional.txt

Fix for dependency problem - https://github.com/pycaret/pycaret/issues/1971#issuecomment-1331449447 described in this issue 
Closes https://github.com/pycaret/pycaret/issues/1971
Adding platform spec for scikit-learn-intelex package as it's available only for x86 platform 
would be tested as part of product build/packaging
scikit-learn-intelex package would be requested only for x86 platform 

Enforce X86 platform spec for scikit-learn-intelex package

---

pycaret/internal/preprocess/time_series/forecasting/preprocessor.py

Fixes this warning
```
2022-12-03 15:32:47,833:WARNING:C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_14p0\lib\site-packages\sktime\transformations\series\compose.py:17: DeprecationWarning: transformations.series.compose is deprecated and will be removed in version 0.15.0. All estimators in it will be moved to transformations.compose. Please change imports to transformations.compose to avoid breakage.  
```
existing unit tests to pass

resolved FutureWarning

---

.github/workflows/test.yml
pycaret/time_series/forecasting/functional.py
pycaret/time_series/forecasting/oop.py
pycaret/utils/time_series/__init__.py
tests/benchmarks/test_time_series_sp_detection.py
tests/test_time_series_exogenous.py
tests/test_time_series_feat_eng.py
tests/test_time_series_indices.py
tests/test_time_series_metrics.py
tests/test_time_series_plots.py
tests/test_time_series_preprocess.py
tests/test_time_series_setup.py
tests/test_time_series_utils_forecasting_pipeline.py
tests/time_series_test_utils.py

Closes #2175
Closes #1408
- Added the ability in time series to automatically detect the seasonal period. This is an important enhancement since it will not longer need users to enter a seasonal period when the index is not of type `PeriodIindex` or `DateTimeIndex`. Also removes the reliance on the index frequency to set the seasonal period by default and switches to using statistical tests instead.
- Added a benchmarking module in unit tests. 
- Currently, it includes benchmarks for time series seasonal period autodetection.
- Later, we could add benchmarks for regression, classification, etc. as well.
- Unit tests have been added
- Benchmarks tests have been added

Auto Seasonal Period Detection

---

pycaret/containers/models/time_series.py
pycaret/time_series/forecasting/functional.py
pycaret/time_series/forecasting/oop.py
pycaret/utils/time_series/__init__.py
tests/benchmarks/test_time_series_sp_detection.py
tests/test_time_series_setup.py
tests/test_time_series_utils.py

* Follow up to https://github.com/pycaret/pycaret/pull/3151
* This PR allows the ability for the user to filter out the harmonics and only use the base seasonal period (similar to what is done in KATS and what is derived from ACF and Periodograms manually).
* e.g. if seasonal periods detected are 6, 12, 24. Then filtering harmonics will eliminate 6 and 12 since these are already captured by a period of 24. 
* Also cleaned up internal attributes related to seasonality to make them clear.
- Tests added to benchmark module (TBD)
- Existing tests updated for attribute name changes

Added ability to filter out harmonics in seasonal detection

---

pycaret/time_series/forecasting/oop.py
requirements.txt
tests/test_time_series_setup.py

- Fix for deprecations in sktime 0.15.0
- Pinned sklearn due to API changes in 1.2.0 ([Link](https://scikit-learn.org/1.0/modules/generated/sklearn.linear_model.LinearRegression.html#sklearn.linear_model.LinearRegression))
Existing unit tests to pass

fix for sktime 0.15.0

---

requirements-optional.txt

Pins `pydantic<1.10.3` (spacy dependency) due to https://github.com/pydantic/pydantic/issues/4885, removes a condition causing Ray to not be installed on Python 3.10 (Ray is now available for that version).

Pin pydantic, remove Ray python requirements

---

pycaret/internal/pycaret_experiment/supervised_experiment.py

Closes https://github.com/pycaret/pycaret/issues/3178
Returns non-transformed dataframe instead of transformed one in `predict_model`, matching the behavior in Pycaret 2.0.

Return unmodified dataframe in `predict_model`

---

pycaret/internal/preprocess/iterative_imputer.py
tests/test_preprocess.py

Edge case in `IterativeImputer` caused an exception if only numerical or only categorical columns were present.
Closes https://github.com/pycaret/pycaret/issues/3227
The `statistics_` attribute will not be present on `SimpleImputers` that were not fitted if there were no columns with required dtype. This PR uses `getattr` with a default value to avoid an exception. Test case added.

Fix IterativeImputer if only one data type is used

---

requirements-optional.txt
tests/test_classification_engines.py
tests/test_regression_engines.py

Pin sklearnex to 2023.0.1 and upper
Remove dpcpp-cpp-rt
Implements https://github.com/intel/scikit-learn-intelex/issues/1158
Solves fails: https://github.com/pycaret/pycaret/actions/runs/3921915807/jobs/6704526852
Update to 2023.0.1 version of scikit-learn-intelex which doesn't require dpcpp-cpp-rt to run.
Local run of sklearn tests for SVM with sklearnex 2023.0.1 and without installed dpcpp-cpp-rt: no device availability exceptions appeared.
N/A

Update sklearnex requirements

---

pycaret/time_series/forecasting/functional.py
pycaret/time_series/forecasting/oop.py
pycaret/utils/time_series/forecasting/model_selection.py
tests/test_time_series_indices.py

Closes #3270
When a column is passed as an index, previously, it was coerced to DatetimeIndex/TimeIndex irrespective of the column type. With this change, if it is of type integer, it will not be coerced and the integer type will be preserved.
More modular unit tests added for index handling, plus existing unit tests to pass

[Time Series] Fixed handling of integer indices through data frame column

---

pycaret/internal/plots/yellowbrick.py

Closes https://github.com/pycaret/pycaret/issues/2659
Uses yellowbrick method instead of `plt.savefig` directly to make sure the plot is saved with all elements.

Fix yellowbrick plots being saved without legend

---

pycaret/utils/time_series/__init__.py
requirements.txt

sktime 0.16.1 fixed an issue related to seasonality calculations in edge cases. This was patched earlier inside pycaret. Now that patch has been removed.
- Failing unit test passes locally. 
- All units tests to pass on GitHub

fix for sktime 0.16.1 release

---

.gitignore
pycaret/internal/pycaret_experiment/supervised_experiment.py

Fix for #3331.
Closes #[3331]
Added weights variable in the following piece of code of supervised_experiment.py
if self._ml_usecase == MLUsecase.CLASSIFICATION:
model = voting_model_definition.class_def(
estimators=estimator_list, voting=method, n_jobs=self.gpu_n_jobs_param
estimators=estimator_list,
voting=method,
weights=weights,
n_jobs=self.gpu_n_jobs_param,
)
Also added updated .gitignore
I ran the piece of code presented in Issue # 3331, and now it show the weights used instead of None. Before the change, the voting classifier was giving each classifier the same weight but now it give the weights which is provided by the user because it shows the provided weights when you print the …

Fix weights not being set in `blend_models`

---

pycaret/classification/oop.py
pycaret/regression/oop.py
tests/test_preprocess.py

Closes https://github.com/pycaret/pycaret/issues/3324
Moves `CleanColumnNames` to be the last step in the pipeline before the estimator. Otherwise, the column names we have mapped to data types in `self._fxs` get mismatched and cause issues with preprocessors later on.

Move `CleanColumnNames` to the end of pipeline

---

pycaret/internal/logging.py
pycaret/internal/metrics.py
requirements.txt

Closes https://github.com/pycaret/pycaret/issues/3351
Closes https://github.com/pycaret/pycaret/issues/3273
This PR introduces two changes:
1. The output from C-level libraries and child processes (spawned by eg. joblib) is now correctly redirected to loggers. The `LoggerWriter` has also been improved.
2. Metrics will warn if there was an error on fit.
This PR adds a single new dependency, which is already a dependency of one of the other dependencies, so there shouldn't be any issues.
**original …

Redirect C-level and child output, warn on metric failure

---

pycaret/time_series/forecasting/functional.py

Closes #3405 
Change was made to oop interface already, but missed making it to functional API earlier. This change has been made now.
Existing tests to pass on GitHub CI.

made oop and functional API same

---

pycaret/internal/pycaret_experiment/tabular_experiment.py

Closes #3422 
This PR updates the ImportError message when using `use_gpu="force"` and cuML is not available. The message "Install or update cuML to be >= 22.10" is clear enough without trying to reference the current version installed.
It also adds a note about installation instructions.
Tested locally by creating a fresh environment and installing PyCaret via pip, via Github (master branch), and via this PR's local branch.
```
mamba create -n pycaret -c conda-forge python=3.10 jupyterlab ipython
conda activate pycaret
python -m pip install .
```
```python
data = get_data('diabetes')
s = setup(data, target = 'Class variable', use_gpu="force")
------------------------------------------------------------------------- …
```

Cleanup cuML ImportError message

---

requirements-optional.txt

In https://github.com/evidentlyai/evidently/pull/550 old API will be removed, so you need to restrict evidently version before you switch to new API

Restrict evidently version

---

pycaret/internal/preprocess/transformers.py

Closes #3469
Fixes a bug where non numerical array checks would fail when `get_feature_names_out` is not available in a transformer.

fix np array check  when get_feature_names_out is unavailable

---

pycaret/loggers/base_logger.py
pycaret/loggers/dagshub_logger.py

DagsHub Logger supports programmatic logging (won't be blocked by the authentication process)
1. Nested run issue: when running `compare model` with either mlflow logger or dagshublogger, the next algorithm experiment will be logged nested in the previous experiment.
2. Incorrect URL splitter: #3435 
Closes #3435 
By running `dagshub.init()` before the setup(), users can programmatically log the experiments without interrupt by the authentication.
```
dagshub.init(repo_name, repo_owner)
```
1. Nested run issue: The nested run in `compare_model` happens because of raising an error in `_construct_pipeline_if_needed`, which led to the failure of ending the active run. The fix is to add the `self` in the function argument.
2. Incorrect URL splitter: replace the `os.sep()` splitter to `"/"` …

DagsHubLogger: support programmatic logging / Bug Fix: incorrect url splitter, mlflow nested run

---

pycaret/utils/time_series/forecasting/pipeline.py
tests/test_time_series_utils_forecasting_pipeline.py

Upgrade to sktime 0.19.1 needs some changes to the internal pipeline. This PR is an intermediate PR to make sure that if we make a change to the pipeline for 0.19.1, that it does not break functionality for older versions <= 0.17.0

prep for pipeline change needed when we upgrade sktime to 0.19.1

---

docs/source/tutorials.rst

The links to Jupyter notebooks in the [Tutorial page](https://pycaret.readthedocs.io/en/latest/tutorials.html) are currently dead. I fixed them to point to the correct files on the main repo. 
I also added a link to the Time Series Forecasting tutorial notebook, which was missing from the list of tutorials.

Fixed dead links in Tutorial docs

---

.github/workflows/test.yml
pycaret/containers/models/time_series.py
requirements.txt
tests/test_time_series_preprocess.py

Tests were failing on CI for time series and other modules. This PR is to fix the time series tests.
- `sktime` `BoxCoxTrandformer` supports negative values in recent versions. Hence, tests have been updated appropriately
- Recent versions of sktime introduced a legacy interface argument. This needs to be incorporated in Prophet Patched class in pycaret.
- Pinned sktime upper limit for now. Once the new interface is supported (along with older interface - depending on sktime version), we can remove the limit.
Failing time series unit tests have been checked locally for sktime vesions 0.19.1 and 0.21.0.

Fix for sktime changes in recent versions

---

pycaret/classification/oop.py
pycaret/internal/preprocess/preprocessor.py

(new PR due to some internal difficulties)
Closes #3638
Added `random_state` functionality to class imbalance transformers for reproducible results
NA

[BUG]: Enable `random_state` for class imbalance

---

pycaret/time_series/forecasting/functional.py
pycaret/time_series/forecasting/oop.py

Closes: #3669
Enabled a safe `if` check when running `fig.show()` during TimeSeries experiments. Without this change, then plots will be printed twice when we set the parameter: `return_fig=True`.
Full description included in:
- #3669
No. It wasn't a bug previously, only a logical issue.
NA

Resolve double-printed plots during ts experiment

---

requirements-optional.txt

Closes #3721
Tests are failing on GitHub due to nixtla statsfoecast deprecating parallel argument in AutoARIMA in 1.6.0 (https://github.com/Nixtla/statsforecast/issues/576). This has also been reported to sktime: https://github.com/sktime/sktime/issues/5207
Limited statsforecast version to < 1.6.0
Tests pass locally now. Should also pass on GH

limiting statsforecast due to deprecation of parallel argument

---

pycaret/internal/preprocess/iterative_imputer.py

Closes #3741 
Iterative imputation didn;t handle dataframe indices correctly. this fixes it

fix index handling with iterative imputer

---

pycaret/internal/pycaret_experiment/supervised_experiment.py

Closes #3738
Errors in compare_models are now properly raised when `errors=True`.

fix error raise in compare_models

---

pycaret/internal/pycaret_experiment/supervised_experiment.py
pycaret/time_series/forecasting/oop.py

Closes #3789
* Changes some calls to include explicit args
* used kwargs to catch unused args in TS function definition
Unit tests pass locally (some basic ones), rest all to pass in GH

switched to non-positional explicit args and kwargs to catch them

---

.github/workflows/test.yml
requirements.txt

Hi again,
in order to support GH-3756, this patch demonstrates that running the test suite succeeds on Python 3.11 without much ado, by permitting an installation of a more recent version of NumPy. This will probably also open the door for eventually thinking about upgrading pandas.
We exercised it at [^1] already, where Python 3.11/Linux succeeded, and we think the test suite failing on Windows 3.8 might be unrelated. Maybe you can have a closer look?
With kind regards,
Andreas.
[^1]: https://github.com/crate-workbench/pycaret/actions/runs/6762683108

Dependencies: Permit NumPy up to 1.26. CI: Run Python 3.11 on `test_linux` workflow.

---

.github/workflows/test.yml
pycaret/internal/pycaret_experiment/tabular_experiment.py
requirements-optional.txt
tests/test_overflow.py

Based on GH-3813 and GH-3756, this patch aims to activate Python 3.11 across the board, modulo Dockerfiles.
-- https://github.com/crate-workbench/pycaret/actions/runs/6763789876
Fix error on Python3.11/Windows. pytest does not even start.
```python
Run pytest --durations=0
ImportError while loading conftest 'D:\a\pycaret\pycaret\tests\conftest.py'.
tests\conftest.py:4: in <module>
import pycaret.anomaly.functional
E   ModuleNotFoundError: No module named 'pycaret'
Error: Process completed with exit code 1.
```
-- https://github.com/crate-workbench/pycaret/actions/runs/6763789876/job/18381329119#step:7:15

More Python 3.11 support

---

.github/workflows/test.yml
pycaret/internal/pycaret_experiment/tabular_experiment.py
requirements-optional.txt
setup.cfg
tests/benchmarks/test_memory_performance.py
tests/benchmarks/test_time_series_sp_detection.py
tests/test_classification_plots.py
tests/test_classification_tuning.py
tests/test_clustering.py
tests/test_create_api.py
tests/test_create_docker.py
tests/test_overflow.py
tests/test_regression_plots.py
tests/test_regression_tuning.py
tests/test_time_series_models.py
tests/test_time_series_plots.py
tests/test_time_series_tune_grid.py
tests/test_time_series_tune_random.py
tests/test_time_series_utils_plots.py

Hi Antoni,
while working on GH-3814, we discovered the style of running specific groups of test cases by removing files from the `tests/` folder. This patch steers that detail into a different direction, by using pytest markers and pytest.skip() annotations instead. We hope you like that approach.
In this spirit, by using this style of discriminating the test cases within the CI/GHA workflow definition file, it becomes much easier to maintain.
With kind regards,
Andreas.
- https://docs.pytest.org/en/7.1.x/how-to/mark.html
- https://docs.pytest.org/en/7.1.x/example/markers.html

Optimize CI

---

LICENSE
setup.py

Updated the copyright header in all/applicable files to correctly reflect copyright attribution to the PyCaret project and contributors.
Main changes:
- Replaced the copyright line to 'Copyright (C) 2019-2024 PyCaret'.
- added a line to indicate the main author: 'Author: Moez Ali (moez.ali@queensu.ca)'.
- included a line to reference all contributors: 'Contributors (https://github.com/pycaret/pycaret/graphs/contributors)'.
This update complies with the PyCaret project's copyright attribution practices and provides clear author and contributor information.
Future tasks:
- Check other files to ensure consistency in copyright headers.

Update copyright headers

---

pycaret/internal/pycaret_experiment/supervised_experiment.py
requirements-optional.txt
requirements.txt

I recently started seeing a problem in pycaret tests, ModuleNotFoundError: No module named 'evidently.dashboard'
After investigating, I discovered that the code used in Pycaret to use evidetly is very old, so it was necessary to update the Pycaret code.
For better context: I was unable to use an old version of evidently because it forced me to change all pycaret dependencies to older versions, in other words, a conflict of dependencies was generated. The only solution is to use recent (and modern) versions
I also asked for help at https://github.com/evidentlyai/evidently/issues/1010

Upgrade old evidently api to new api

---

pycaret/internal/logging.py

The logs.log file is automatically generated in the import script directory (by pycaret/internal/logging.py). This creates problems when the directory is not writable, like AWS Lambda.
I particularly have problems using it directly in the lambda with a container, as the only free directory to write to is '/tmp'.
This update is correctly saving to the desired path.
I found other reports like issue #1057.
Closes #1057
I created a new variable 'logPath' and assigned it an environment variable (PYCARET_CUSTOM_LOGGING_PATH), similar to the one already used for the log level (PYCARET_CUSTOM_LOGGING_LEVEL).
I changed the name of the file ‘logs.log’ to this variable, which takes the path informed in the environment variable and if it doesn’t exist, it continues as ‘logs.log’
Please delete options …

Custom path for logging (logs.log)

---

.gitignore
requirements.txt

PyCaret uses the private functions `joblib.memory._format_load_msg` and `FastMemorizedFunc._get_output_identifiers` from Joblib, which are no longer present in Joblib 1.4.
- https://github.com/pycaret/pycaret/issues/3959
In order to fix the problem without much efforts, this patch just downgrades to Joblib 1.3.x without further ado.
It is advisable to release this update on behalf of a bugfix release, so that downstream users will get this issue resolved quickly.
In order to use the patch instantly before upstream maintainers ran a new bugfix release, if it's important to you, you may want to use this pip package specification to install the package in an ad hoc manner, including the fixes for both dependency flaws.
```console
pip install --upgrade 'pycaret[parallel] @ …
```

Fix dependency: Joblib 1.4.0 breaks PyCaret, so downgrade to <1.4

---

pycaret/internal/memory.py

- https://github.com/pycaret/pycaret/issues/3977
- Do not use from joblib import _format_load_msg
- it's private and now removed. 
Closes #3977
- removed joblib._format_load_msg() usage

Update memory.py - removing joblib._format_load_msg() usage

---

pycaret/containers/metrics/classification.py
pycaret/internal/metrics.py
pycaret/internal/pipeline.py
tests/test_classification.py
tests/test_regression.py

some details have not been updated to support the latest scikit-learn 1.4 code
- confirm/update code
- fix errors
- make sure tests are testing metrics correctly (needs create more tests?)
Closes #3932

Fix AUC metric

---

pycaret/time_series/forecasting/oop.py

This pull request addresses an issue in the TSForecastingExperiment class where a ZeroDivisionError could occur in the _set_seasonal_type method. The error happens during the calculation of the seasonality strength (Fs_add and Fs_mult) when the denominator is zero.
References:
Issue: [#3997](https://github.com/pycaret/pycaret/issues/3997)
when a time series df with same value across all timeframes are given to the setup experiment, then it throws error
Closes #3997 
Added conditional checks to avoid division by zero in the _set_seasonal_type method.
The values of Fs_add and Fs_mult are now set to 0 if their respective denominators are zero.
These changes ensure that the method handles cases with zero variance in the residuals and seasonal components without causing runtime errors. The …

Fix ZeroDivisionError in _set_seasonal_type Method

---

pycaret/internal/preprocess/preprocessor.py

Closes #4039
Simply added `.reset_index(drop=True)` after the `pd.concat` operation.  
NA 
NA

Reset index after concatenating train and test dataframes

---

requirements.txt

scikit-plot hasn't been updated in 6 years, so I found a fork to keep the package up to date: mljar-scikit-plot (https://github.com/mljar/mljar-scikit-plot)

Update scikit-plot to mljar-scikit-plot

---

pycaret/internal/pycaret_experiment/supervised_experiment.py

The [DataFrame.map()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html#pandas.DataFrame.map) been added and [DataFrame.applymap()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.applymap.html#pandas.DataFrame.applymap) has been deprecated. [DataFrame.map()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html#pandas.DataFrame.map) has the same functionality as [DataFrame.applymap()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.applymap.html#pandas.DataFrame.applymap), but the new name better communicates that this is the [DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame) version of [Series.map()](https://pandas.pydata.org/docs/reference/api/pandas.Series.map.html#pandas.Ser …

Fix: AttributeError: 'Styler' object has no attribute 'applymap'

---

pycaret/regression/functional.py
pycaret/regression/oop.py

I did adjust the docstring document example in regression module. Before it is is showing an classification example that do not reflect the module task of regression.
I changed to reflect regression example on regression data 'insurance' in both functional.py and oop.py. Removing the juice and classification module.
Before
data: Juice
model: classification
target: Purchase
After
data: insurance
mode: regression
target: charges
It just change the data example, name of data, and regression task not classification

docstring adjustment on regression module

---

pycaret/parallel/fugue_backend.py
tests/test_classification_parallel.py

Details of bug can be found here: #[[4028](https://github.com/pycaret/pycaret/issues/4028)]
Closes #[[4028](https://github.com/pycaret/pycaret/issues/4028)]
I added handling a case when no model was trained (for each model pandas dataframe is empty). It should cover cases when no model was trained as well as training all models failed.
**I am not sure**.
I added one unit test: `test_classification_parallel_returns_empty_models_list_when_no_model_is_trained`.
`NA`
No screenshot.

Fix: In parallel mode return empty list of models when no models was trained.

---

pycaret/anomaly/functional.py
pycaret/classification/functional.py
pycaret/classification/oop.py
pycaret/clustering/functional.py
pycaret/containers/metrics/base_metric.py
pycaret/containers/metrics/clustering.py
pycaret/internal/logging.py
pycaret/internal/metrics.py
pycaret/internal/patches/sklearn.py
pycaret/internal/pycaret_experiment/pycaret_experiment.py
pycaret/internal/pycaret_experiment/supervised_experiment.py
pycaret/internal/pycaret_experiment/unsupervised_experiment.py
pycaret/parallel/fugue_backend.py
pycaret/regression/functional.py
pycaret/regression/oop.py
pycaret/time_series/forecasting/functional.py
pycaret/time_series/forecasting/oop.py
pycaret/utils/generic.py

As per official documentation (https://docs.python.org/3.9/library/typing.html#typing.Callable), typing.Callable is deprecated in favour of collections.abc.Callable. This PR makes the corresponding changes in the imports.
I also updated/created the headers with references to the authors. In case there are no references to the module's author, I created the default header with author Moez Ali.
To do: module authors must update the headers with their names!

[MNT] Update Callable import from typing to collections.abc

---

pycaret/classification/oop.py
pycaret/internal/display/progress_bar.py
pycaret/internal/patches/sklearn.py
pycaret/utils/time_series/__init__.py
tests/benchmarks/test_memory_performance.py

CI currently fails on the linting workflow, which uses flake8, [like this](https://github.com/pycaret/pycaret/actions/runs/13234026192/job/36935724677#step:5:45):
```
pycaret/classification/oop.py:2714:72: E226 missing whitespace around arithmetic operator
pycaret/utils/time_series/__init__.py:248:37: E226 missing whitespace around arithmetic operator
tests/benchmarks/test_memory_performance.py:66:100: E226 missing whitespace around arithmetic operator
tests/benchmarks/test_memory_performance.py:87:114: E226 missing whitespace around arithmetic operator
tests/benchmarks/test_memory_performance.py:157:114: E226 missing whitespace around arithmetic operator
```
- The patch includes and supersedes GH-4125.

[MNT] Fix flake8 linter errors

---

.github/workflows/test.yml

This little patch adjusts the `test` CI job to run the workflow also on stacked PRs (not just PR to `master`).
This helps when staging multiple PRs at the same time.

[MNT] CI: Run test workflow also on stacked PRs

---

.github/workflows/lock_old_threads.yml

There is an erroneous GHA workflow file, introduced by c62c2bfde23.
- Invalid workflow file: `.github/workflows/lock_old_threads.yml#L5`.
You have an error in your yaml syntax on line 5.
- Error: No event triggers defined in `on`.
Deactivate that particular workflow by using `on: workflow_dispatch`, as [suggested](https://safjan.com/quick-ways-to-disable-github-actions-workflows-without-deletion/).

CI: Properly disable "Lock Old Threads" workflow

---

pycaret/internal/preprocess/preprocessor.py
pycaret/internal/preprocess/transformers.py

**Summary:**
This PR fixes a bug in the `_prepare_train_test` method of the `Preprocessor` class, where duplicate indices were not correctly detected when `test_data` was provided. The previous behavior applied `reset_index(drop=True)` before calling `_set_index`, which dropped duplicates in the index before validation, causing the `test_duplicate_indices` test to fail (example: `FAILED: DID NOT RAISE <class 'ValueError'>`).
**Tests:**
- The existing test `tests/test_preprocess.py::test_duplicate_indices` now passes, confirming that the change fixes the behavior.

[BUG] Fix duplicate index detection

---

pyproject.toml

Bump SHAP version to 0.46.0
Closes https://github.com/pycaret/pycaret/issues/4149

[MNT] Bump SHAP version to 0.46.0
