pycaret/pycaret

- classification.py
* added n_jobs =-1 bug #58 
* added training time + MCC #53 
* Highlight Mean Row as Green
> n_jobs =-1 + training_time + MCC

- setup.py
meh, just having 1 more free commit with version update :\
Since pycaret will become version 1.0.1 with this branch, I updated setup.py to match its new version
> update pycaret version

- regression.py
* added n_jobs =-1 bug #58 
* added training time  #53 
* Highlight Mean Row as Green
> Adding Training time +mean in green + n_job=-1

- classification.py
- clustering.py
- regression.py
Changes have only been made to the classification module. If these look acceptable, I can make them to the regression module as well.
https://github.com/pycaret/issues/90
> enhancement for classification models per issues/90

- pycaret/preprocess.py
infinity values & Integer column name issues fixed
> Dev 1.0.1 , Infinity Values and Int Column Names 

- doc/Makefile
- doc/make.bat
- doc/source/conf.py
- doc/source/index.rst
Hi
I have added the support for documentation using sphinx. You can generate the static html files on your system after installing sphinx using 
```
cd doc
make html
```
The site looks like this:
If you would like to publish the docs at readthedocs then I can help. Make me a collaborator there after making your account
Thanks and hope it helps
> Continuous Documentation support

- examples/PyCaret 2 Text Similarity Classification.ipynb
Added Text Similarity Classification using Classification and NLP modules together.
> Added Text Similarity Classification Example

- pycaret/classification.py
- pycaret/regression.py
Refactors by removing duplicates of code generating final display in `setup()` in classification and regression. No functionality has been changed.
> Remove duplicate code in setup()

- pycaret/classification.py
> Update classification.py to solve error in Imbalanced learn. 

- pycaret/anomaly.py
- pycaret/arules.py
- pycaret/classification.py
- pycaret/clustering.py
- pycaret/nlp.py
- pycaret/regression.py
> Clarify that data must be a pandas.DataFrame throughout docstrings

- README.md
There is no change, but just in case.
> Apply syntax highlighting to commands in README.md

- pycaret/classification.py
- pycaret/regression.py
> Fix test_size in train_test_split when sampling=True

- pycaret/arules.py
- pycaret/classification.py
- pycaret/regression.py
> Check data is pd.DataFrame in setup of arules, classification, regression

- pycaret/tests/test_anomaly.py
- pycaret/tests/test_arules.py
- pycaret/tests/test_classification.py
- pycaret/tests/test_clustering.py
- pycaret/tests/test_regression.py
Comparing the code content, this comment is probably unnecessary.
`#compare_models_test`
> Remove unnecessary comments

- docs/source/conf.py
This should make the order in RTD the one we want.
> Sort methods by the order they are found in files

- pycaret/utils.py
11/13 of the evaluation values, that is, `from sklearn import metrics` to be implemented in almost all cases, is summarized.
> Moved multiple imports into one

- pycaret/regression.py
Add missing scale to residuals in regression - forgot this line in the first PR
> Add missing scale to residuals in regression

- pycaret/preprocess.py
Quick fix for reproducible error, added random seed for permutation as @pycaret suggest.
> Fix boruta-algorithm reproduce error #362 #468

- pycaret/classification.py
- pycaret/preprocess.py
- pycaret/regression.py
Fixes some grammar issues/typos in boruta docstrings for greater readability.
Tweaks the boruta if in PreprocessPartOne to be more robust.
> Tweak boruta docstrings

- datasets/index.csv
- datasets/us_presidential_election_results.csv
> Add us_presidential_election_results data

- pycaret/classification.py
- requirements.txt
Fixes parameter imbalance not being fixed before post-CV fitting of training data.
> Fix parameter imbalance before final model fit

- datasets/index.csv
https://github.com/pycaret/pycaret/issues/526#issuecomment-679031586
> fix a typo about extra space

- pycaret/preprocess.py
Fixes https://github.com/pycaret/pycaret/issues/331 properly.
> Support for pandas Categorical dtype in preprocessing

- pycaret/anomaly.py
- pycaret/classification.py
- pycaret/clustering.py
- pycaret/preprocess.py
- pycaret/regression.py
Solves https://github.com/pycaret/pycaret/issues/152
> Add an option to fill numerical NaNs with 0s

- pycaret/preprocess.py
Fixes https://github.com/pycaret/pycaret/issues/533, simplifies OHE by using only sklearn's encoder instead of both sklearn and pandas and cleans the code a little, making a few parts in Auto_Infer conform to pandas convention without changing functionality.
> Bool preprocess fix

- pycaret/tests/test_regression.py
Fix classification import in test_regression.py
> Fix classification import in test_regression.py

- pycaret/classification.py
Simplified `None` checks with an inline ternary operator and boolean expressions.
> Inline ternary operator and boolean expressions

- pycaret/classification.py
Set one-liner for `if silent: sampling = False` and switched from `if-elif` to dictionary lookup.
> Inline if and dictionary mapping

- pycaret/classification.py
> Remove unused dependencies from classification.py

- README.md
- pycaret/classification.py
- pycaret/containers/base_container.py
- pycaret/containers/metrics/classification.py
- pycaret/containers/models/classification.py
- pycaret/internal/utils.py
- pycaret/preprocess.py
- pycaret/regression.py
- pycaret/tests/test_categorical_features.py
- pycaret/tests/test_multiclass.py
- pycaret/tests/test_preprocess.py
- pycaret/tests/test_regression.py
- pycaret/tests/test_remove_outliers.py
- pycaret/utils.py
- requirements.txt
- Enables the user to pass custom pipeline steps that will be applied before model fitting
- Removes OvR, adds new plot (updates from master)
> 2.2 refactor, classification module (#515)

- pycaret/classification.py
- pycaret/containers/base_container.py
- pycaret/containers/metrics/base_metric.py
- pycaret/containers/metrics/classification.py
- pycaret/containers/models/base_model.py
- pycaret/containers/models/classification.py
- pycaret/internal/plotting.py
- pycaret/internal/utils.py
- pycaret/tests/test_classification.py
- pycaret/tests/test_multiclass.py
- pycaret/tests/test_regression.py
Add n_select for compare_models back in
> 2.2-Refactor

- pycaret/preprocess.py
Fixes to datetime and dtype inference + performance improvements.
> Preprocessing fixes

- pycaret/classification.py
- pycaret/internal/Pipeline.py
- pycaret/internal/distributions.py
- pycaret/internal/tune_sklearn_patches.py
- pycaret/internal/utils.py
* patch in early stopping for tune-sklearn
* fix error with hyperopt Integer distributions
> 2.2 refactor patch in early stopping for tune-sklearn

- pycaret/classification.py
- pycaret/containers/models/base_model.py
- pycaret/containers/models/classification.py
- pycaret/containers/models/regression.py
- pycaret/internal/Display.py
- pycaret/internal/persistence.py
- pycaret/internal/utils.py
- pycaret/preprocess.py
Added `Iterative_Imputer` (still needs extra params in setup), Colab display now working, some other fixes
> Pin imbalanced-learn 0.6.2, fix xgboost exception

- pycaret/classification.py
- pycaret/containers/models/classification.py
- pycaret/internal/utils.py
- pycaret/preprocess.py
> 2.2-refactor fixes

- pycaret/classification.py
> 2.2-refactor Predict fix

- pycaret/classification.py
- pycaret/containers/models/classification.py
- pycaret/preprocess.py
- pycaret/tests/test_ignore_low_variance.py
> 2.2-refactor cuML tweaks

- pycaret/classification.py
- pycaret/containers/models/classification.py
- pycaret/preprocess.py
Tweak tune grids, disable BOHB in tune_model, tweaks to iterative imputer
> 2.2-refactor work

- pycaret/classification.py
- pycaret/containers/models/classification.py
> 2.2-refactor catboost tweaks

- pycaret/internal/patches/tune_sklearn.py
- pycaret/internal/supervised.py
- pycaret/internal/utils.py
> Type fix, disable logging

- pycaret/containers/metrics/anomaly.py
- pycaret/containers/models/anomaly.py
- pycaret/containers/models/classification.py
- pycaret/containers/models/regression.py
- pycaret/internal/tabular.py
- pycaret/internal/tunable.py
> 2.2-refactor display change

- pycaret/classification.py
- pycaret/internal/tabular.py
- pycaret/regression.py
> 2.2-Refactor tree plot

- pycaret/anomaly.py
- pycaret/classification.py
- pycaret/clustering.py
- pycaret/containers/metrics/regression.py
- pycaret/containers/models/anomaly.py
- pycaret/internal/persistence.py
- pycaret/internal/plotting.py
- pycaret/internal/tabular.py
- pycaret/internal/utils.py
- pycaret/nlp.py
- pycaret/regression.py
- pycaret/tests/test_custom_pipeline.py
> 2,2-refactor work

- .github/workflows/test.yml
> Disable tuning tests

- pycaret/internal/preprocess.py
> Fix special chars in iterative imputation

- pycaret/internal/pipeline.py
> Fix internal pipeline

- pycaret/internal/patches/yellowbrick.py
- pycaret/internal/plotting.py
- pycaret/internal/tabular.py
- pycaret/utils.py
> Fix plots, check_metric

- pycaret/internal/utils.py
> get_cv_splitter behavior change

- pycaret/internal/tabular.py
> Raise error if fold_groups has NaNs

- pycaret/anomaly.py
- pycaret/internal/tabular.py
- pycaret/internal/utils.py
- pycaret/regression.py
> Fixes, get_anomaly

- setup.py
- setup_nightly.py
> full install option

- pycaret/anomaly.py
- pycaret/classification.py
- pycaret/clustering.py
- pycaret/internal/tabular.py
- pycaret/regression.py
> Fix predict_model for unsupervised

- pycaret/internal/tabular.py
> Fix load_config

- pycaret/internal/tabular.py
> Add missing global

- pycaret/internal/tabular.py
> Fix globals

- pycaret/internal/cuml_wrappers.py
> Handle for cuml wrappers

- pycaret/internal/cuml_wrappers.py
> More missing cuML fields

- pycaret/classification.py
- pycaret/internal/tabular.py
- pycaret/regression.py
- pycaret/tests/test_classification_plots.py
- pycaret/tests/test_regression_plots.py
Adds an option to use train data for supervised plots.
> Train data for plots

- pycaret/internal/tabular.py
Updated optimize_threshold function to increase grid range from 0.00 - 0.99 to 0.0000 - 0.9999 to align with default 4 decimal places variables. Also, made the t variable to a float so it can be accepted in the predict module.
> updated optimize_threshold (grid, float)

- pycaret/arules.py
made changes in the examples so they can be copy/pasted and run as is
**changed:**
`france = get_data('france')` to `data = get_data('france')`
`item_id = 'ProductName'` to `item_id = 'Description'`
**added:**
`exp_name = setup(data = data, transaction_id = 'InvoiceNo', item_id = 'Description')` to the example in `plot_model()`
> Fixed small issues in the docstring examples

- pycaret/internal/preprocess.py
If there are columns with non-string names in the test dataframe, things will break. This PR fixes this issue.
> Fix issues with non-string columns in a df

- pycaret/internal/preprocess.py
- pycaret/tests/test_preprocess.py
- requirements.txt
- Added unit tests for simple imputer to make sure the imputer works correctly and is compatible with the sklearn pipeline. 
- Fixed the issue that time dtype is not imputed correctly.
> Added unit tests for simple imputer and fixed minor issues

- pycaret/internal/tabular.py
- Fixed the cutoff of long text in png graphs, such as the shap graphs and the feature importance graph
> Fixed the cutoff of long text in png graphs

- pycaret/tests/test_utils.py
- pycaret/utils.py
- Add tests for cases that didn't exist previously
- Remove unnecessary imports
> Add tests for pycaret/utils.py

- pycaret/internal/persistence.py
https://github.com/pycaret/pycaret/issues/922
> #922 load_model (s3)

- pycaret/internal/plotting.py
- pycaret/internal/tabular.py
> yellowbrick streamlit support

- pycaret/containers/models/classification.py
- pycaret/containers/models/regression.py
- pycaret/internal/tabular.py
- pycaret/internal/tunable.py
> Return base sklearn objects instead of tunables

- pycaret/internal/preprocess.py
- pycaret/tests/test_preprocess.py
- Fixed Dummify for satisfying sklearn's pipeline structure.
- Added an unit test for testing the complete pycaret preprocessing pipeline.
- Added Preprocess_Path_One_Sklearn for testing: This is a clone of Preprocess_Path_One with modification on the pipeline for testing purposes. It will be removed when the pipeline is completely refactored.
> Fixed Dummify for satisfying sklearn pipeline structure

- pycaret/internal/plots/helper.py
- pycaret/internal/plots/residual_plots.py
- pycaret/internal/plots/yellowbrick.py
- pycaret/internal/tabular.py
- pycaret/regression.py
This was supposed to be a general plotly support PR, however it appears that it is not possible to reliably convert MPL plots to plotly. Therefore, this PR is just https://github.com/pycaret/pycaret/pull/980 with formatting and minor tweaks.
> Plotly support

- .github/pull_request_template.md
Pull Request for the issue #1020
> Create pull_request_template 

- pycaret/internal/tabular.py
> Fix issue with indices

- pycaret/internal/preprocess.py
- pycaret/tests/test_preprocess.py
- requirements.txt
- Fixed Reduce_Dimensions_For_Supervised_Path for satisfying sklearn pipeline structure.
- All pca methods tested and passed, except for TSNE. This is because that TSNE does not have a transform method (REF: https://github.com/scikit-learn/scikit-learn/issues/5361)
> Fixed Reduce_Dimensions_For_Supervised_Path for satisfying sklearn pipeline

- pycaret/internal/cuml_wrappers.py
> Ridge, RF fixes

- pycaret/containers/models/time_series.py
- pycaret/internal/PycaretExperiment.py
- pycaret/internal/meta_estimators.py
- pycaret/internal/utils.py
- pycaret/tests/test_time_series.py
- pycaret/time_series.py
- test_create_model.py
- test_tune_model.py
Added tune_model capability along with updates for create model
Unit tests have been added
NA
> tune_model + create_model updates

- tutorials/Binary Classification Tutorial Level Beginner -  CLF101.ipynb
> Fix erratum

- pycaret/internal/preprocess.py
Fixes: https://github.com/pycaret/pycaret/issues/1155
> Optimize Fix_multicollinearity

- pycaret/internal/preprocess.py
Fixes: https://github.com/pycaret/pycaret/issues/1166
Ensures that target column for feature selection is float, fixing exceptions with certain datasets.
> Fix `feature_selection` failing with certain datasets

- pycaret/containers/metrics/classification.py
- pycaret/internal/metrics.py
Fixes: https://github.com/pycaret/pycaret/issues/1188
While I couldn't replicate the linked issue locally or during CI, this alternative approach should make the binary-multiclass wrapper pickeable in all cases.
> Alternative Binary-Multiclass wrapper

- pycaret/internal/preprocess.py
Fixes duplicate indices causing an exception in iterative imputation.
> Fixes duplicate indices causing an exception in iterative imputation

- README.md
As the LICENCE was updated to MIT and in the README.md file it was "Copyright 2021-2022 Moez Ali moez.ali@queensu.ca", It may create confussion.
- [x ] This change requires a documentation update
- [
x] My changes generate no new warnings.
**![Screenshot from 2021-05-21 …
> Updated the License to MIT in README.md

- pycaret/containers/models/time_series.py
Added Auto ARIMA model container
Unit tests run
> [FEAT] Auto ARIMA

- CHANGELOG.md
- pycaret/internal/tabular.py
- #1304 issue fixed
Fixes: #1304 
gain and lift plot in the `pycaret.classification` module is changed to `y_true` instead of `y_pred`. Both the `gain` and `lift` function takes `y_true` value along with `predict_proba`. I have confirmed this from the documentation of the `scikitplot`. See below:
- [ X] Bug fix (non-breaking change which fixes an issue)
> fixed bug in gain and lift plot in classification module

- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/tests/test_time_series.py
**Tune Model changes**
**Create Model changes**
**Unit Tests Speedup**
Unit tests added as appropriate
> tune_model fixes and cleanup

- .github/workflows/test.yml
Ref: https://spacy.io/usage/v3#migrating-downloading-models
Fixes: Pycaret failing tests
Pycaret test workflows are failing due to breaking changes made in spacy library.
This PR fixes that.
NA
NA
> [FIX] (.github/workflow/test): Fix spacy deprecation bug

- pycaret/containers/models/time_series.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/tests/test_time_series.py
* Fixes: https://github.com/pycaret/pycaret/issues/1245
* Also fixed a minor bug with error message when the index is not of allowed type and seasonal_parameter is missing
Multiplicative components and dependencies on multiplicative components (e.g. deseasonalizing with multiplicative components) are now disabled when the time series has negative values.
Unit tests have been updated and rerun
> Support for negative values in time series

- pycaret/classification.py
- pycaret/internal/tabular.py
- pycaret/tests/test_classification_plots.py
- #1326
Fixes: #[issue number that will be closed through this PR] #1326
Add KS statistic plot in the plot_model function from scikit-plots.
In statistics, the Kolmogorov–Smirnov test (K–S test or KS test) is a nonparametric test of the equality of continuous (or discontinuous, see Section 2.2), one-dimensional probability distributions that can be used to compare a sample with a reference probability distribution (one-sample K–S test), or to compare two samples (two-sample K–S test). It is named after Andrey Kolmogorov and Nikolai Smirnov.
```
data = get_data('juice') …
```
> add ks_plot in plot_model for classification module

- pycaret/internal/preprocess.py
> Fix Iterative Imputer dtype

- pycaret/containers/models/time_series.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/internal/utils.py
Major changes include: 
1. baseline, classical, linear, neighbors and tree model types available when calling `models()`.  [link](https://github.com/pycaret/pycaret/blob/36cd00a3ac3e1176072e14fbf475d3367214d817/pycaret/internal/pycaret_experiment/time_series_experiment.py#L2360)
2. Cast metrics name to upper case to ensure highlighting minimum value in  `compare_models()`. [link](https://github.com/pycaret/pycaret/blob/36cd00a3ac3e1176072e14fbf475d3367214d817/pycaret/internal/pycaret_experiment/supervised_experiment.py#L655)
> fix: time series model types available

- pycaret/internal/ensemble.py
Minor changes include:
1. Check equal length of input forecasters and provided forecasters. [link](https://github.com/pycaret/pycaret/blob/6493a165156bb8c870cd7a55ded4e5f53204c2b1/pycaret/internal/ensemble.py#L73).
2. Set uniform weight for voting method if not provided. [link](https://github.com/pycaret/pycaret/blob/6493a165156bb8c870cd7a55ded4e5f53204c2b1/pycaret/internal/ensemble.py#L59)
No new tests added. 
> fix: Blend model voting with weight Uniforms

- pycaret/containers/metrics/time_series.py
- Added R2 metric container
Unit tests passed locally
> Added R2 metric container

- pycaret/internal/tabular.py
Now only iterables will be wrapped in a PyCaret distribution
> Tweak custom grid behavior in tune_models

- .github/workflows/test.yml
> Run pytest every day

- CHANGELOG.md
- README.md
- docs/source/index.rst
- pycaret/utils.py
- setup.py
- setup_nightly.py
Bumps version number to 2.3.2, updates readme, changelog
> 2.3.2 update preparations

- pycaret/utils.py
Fixes: https://github.com/pycaret/pycaret/issues/953
Fixes `check_metrics` util function not respecting arguments in the metric container. Thanks @tezansahu for pointing this out!
> Fix check_metric not respecting function args

- pycaret/internal/pycaret_experiment/tabular_experiment.py
Add polynomial_features to preprocessing.
This is my frist trial PR to new preprocessing. Please check if there is any problem. @tvdboom 
NA
> Add polynomial_features to preprocessing

- requirements-optional.txt
> Fix `[full]` install hanging by pinning `interpret<=0.2.4`

- .github/workflows/test.yml
- pycaret/anomaly.py
- pycaret/classification.py
- pycaret/clustering.py
- pycaret/internal/persistence.py
- pycaret/regression.py
- pycaret/tests/test_persistence.py
- requirements-optional.txt
- requirements-test.txt
- setup.py
- setup_nightly.py
https://github.com/pycaret/pycaret/issues/1443
Fixes: #1443
Add support for s3 folder path and the unit test.
- [x ] New feature (non-breaking change which adds functionality)
- [x ] This change requires a documentation update
pytest and moto was used to created mock s3 resource for testing
NA
> add support for s3 folder path and unit test

- pycaret/internal/tabular.py
- requirements-optional.txt
Enables `multivariate` and `constant_liar` features of Optuna TPE sampler. They have been show to improve convergence by respectively taking into account interactions between parameters and ensuring similar combinations are not taken during parallel evaluation (important for tune-sklearn).
> Enable experimental Optuna TPESampler features

- CHANGELOG.md
- README.md
- pycaret/utils.py
- setup.py
- setup_nightly.py
> Prep for 2.3.3

- pycaret/containers/models/time_series.py
- pycaret/internal/ensemble.py
- pycaret/tests/test_time_series.py
Reimplement EnsembleForecaster with sktime>=0.7.0
> fix: blending compatible with sktime 0.7.0

- MANIFEST.in
Conda builds for new release is failing without this file
Add new requirements-test.txt file to the manifest
NA
NA
NA
> Add requirements-test.txt file to manifest

- pycaret/internal/preprocess/preprocess.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
> Add transformation

- pycaret/containers/metrics/time_series.py
- pycaret/containers/models/time_series.py
- pycaret/internal/ensemble.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/tests/test_preprocess.py
- pycaret/tests/test_time_series.py
- pycaret/tests/test_time_series_splitters.py
- requirements-ts.txt
- Upgraded sktime from 0.5.2 to 0.7
Upgrade sktime
Unit Tests pass except preprocessing (since sktime required sklearn 0.24). This preprocessing step has been disabled for now until preprocessing is upgraded.
No
> Ts sktime 0p7

- pycaret/internal/tabular.py
Fixes: https://github.com/pycaret/pycaret/issues/1496
Fixed an issue where custom estimators passed to `blend_models`/`stack_models` didn't get a name assigned, leading to an exception.
- [] New and existing unit tests pass locally with my changes.
> Fix blend/stack for custom estimators

- README.md
Removing the hit counts of the repository as the server is down for the [![HitCount](http://hits.dwyl.io/pycaret/pycaret/pycaret.svg)](http://hits.dwyl.io/pycaret/pycaret/pycaret) see https://github.com/eugeneyan/applied-ml/pull/144
Also adding the (https://badge.fury.io/py/pycaret) with python version
**original screenshot**  
<b>updated screenshot </b>
> removing the git count from readme.md and adding pypi link

- pycaret/internal/tabular.py
Fixes: https://github.com/pycaret/pycaret/issues/1494
Ensures the `errors="ignore"` setting in `compare_models` is respected for full dataset fit of selected models.
> Ensure ignore in `compare_models` works for full fit

- pycaret/internal/preprocess.py
- pycaret/tests/test_preprocess.py
Fixes: #1501
The auto data infer function transforms the target variable into object type if it's Int64, just as all the feature variables, which is not correct. This is fixed now.
A new test, , ```test_auto_infer_label```, is added in test_preprocess.py. This test ensures that when the target variable is Int64, no encoding will be applied to it.
> fix the issue that encodes int64 target variable

- requirements.txt
Fixes a RuntimeError during import due to a numba version being too high.
> Fix installation issues by pinning numba

- pycaret/internal/plots/time_series.py
> Added Time Series Plots

- pycaret/internal/plots/time_series.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/tests/test_time_series.py
- time_series_101.ipynb
- Added diagnostics plot to the wrapper
- Fixes per https://github.com/pycaret/pycaret/issues/1565
- https://github.com/pycaret/pycaret/issues/1565
Unit tests updated and run locally
> Update Plots 

- pycaret/classification.py
- pycaret/internal/tabular.py
- pycaret/regression.py
Improves the new `get_leaderboard` method. Also stops finalized models from being cross-validated and added to master model list.
> Improve `get_leaderboard`

- pycaret/internal/plots/time_series.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
> Ts plot modifications

- pycaret/internal/ensemble.py
- pycaret/internal/plots/time_series.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/time_series.py
- requirements-ts.txt
- time_series_101.ipynb
Fixes: 
#1555
#1563
#1613
#1565 
#1591
Plus further fixes to plotting
Unit tests were rerun
> Further fixes to time series module

- pycaret/anomaly.py
- pycaret/classification.py
- pycaret/clustering.py
- pycaret/regression.py
- pycaret/time_series.py
Fixes: https://github.com/pycaret/pycaret/issues/1558
> Fix `load_model()` not working without running `setup()` first

- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/internal/tests/__init__.py
- pycaret/internal/tests/stats.py
- pycaret/internal/tests/time_series.py
- pycaret/tests/test_time_series.py
- #1590
Changed return data index to columns so we can have a dictionary of settings in there.
Unit tests have been updated
N/A
> Fix Stats Index

- pycaret/internal/tabular.py
Improving error message when ignore column doesn't exist in the dataset. In below you can see the improved version which mentions the column name
> improving error message

- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
Closes: #1783 
Implemented Streamlit support for time series
Unit tests to be rerun on GitHub
> streamlit support per #1783

- docs/source/api/anomaly.rst
- docs/source/api/arules.rst
- docs/source/api/classification.rst
- docs/source/api/clustering.rst
- docs/source/api/datasets.rst
- docs/source/api/nlp.rst
- docs/source/api/regression.rst
- docs/source/api/time_series.rst
- docs/source/index.rst
- docs/source/modules.rst
Adds docs for time series. May need a change in readthedocs config to generate docs for branches other than master.
> Time series docs

- pycaret/internal/pycaret_experiment/time_series_experiment.py
> streamlit fix

- pycaret/containers/models/time_series.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
- Fix for plotting per #1699 (Do not close ticket yet). This is an intermediate fix
- Fix for clashing of different types of naive models per #1812
> Fixes for Time Series Beta Release

- .github/workflows/test.yml
> Test Python 3.9 instead of 3.6

- .github/workflows/test.yml
- pycaret/classification.py
- pycaret/internal/meta_estimators.py
- pycaret/internal/patches/yellowbrick.py
- pycaret/internal/tabular.py
- pycaret/tests/test_probability_threshold.py
Closes https://github.com/pycaret/pycaret/issues/1608
> Add custom probability threshold for binary classification, independent CV for `calibrate_model`

- pycaret/containers/models/time_series.py
Closes #1846
Default cds_dt models (create_models) now take into account sp as well as sp for `window_length`
Unit tests to be run on GitHub
> improved default grid definition for CdsCt per #1846

- pycaret/containers/models/time_series.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/tests/test_time_series.py
- pycaret/tests/time_series_test_utils.py
- pycaret/time_series.py
Closes #1812
Added eq_function to model containers for `naive`, `snaive` and `grand_means` model.
Unit tests run locally
> fix to eq functions for naive models per #1812

- pycaret/internal/tabular.py
> Check sklearn version

- CHANGELOG.md
- README.md
- pycaret/utils.py
- setup.py
- setup_nightly.py
> Bump version to 2.3.5, update changelog

- pycaret/internal/pycaret_experiment/time_series_experiment.py
fix per #1872
Closes #1872
See #1872
Unit tests pass
> fix for wrong arguments to create model

- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/tests/test_time_series.py
Fixes per #1864
Closes #1864
See #1864
Unit tests have been added
> Fixed tuning of custom models

- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/tests/test_time_series.py
- pycaret/tests/time_series_test_utils.py
- pycaret/time_series.py
#1865
Closes #1865
Refer to #1865
Unit tests added and updated
> fix for non-continuous fh per #1865

- pycaret/internal/utils.py
remove duplicated code
remove duplicated code
try:
calculated_metric = score_func(target, labels, **container.args)
except:
try:
calculated_metric = score_func(target, labels, **container.args)
except:
calculated_metric = 0
remove duplicated code
NA
> remove duplicated code

- pycaret/containers/metrics/time_series.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/tests/test_time_series_metrics.py
Closes #1900
Unit tests on GitHub
> Metrics fix for INPI

- requirements.txt
> Fix colab install by pinning pyyaml<6.0.0

- pycaret/anomaly.py
- pycaret/classification.py
- pycaret/clustering.py
- pycaret/internal/helper.py
- pycaret/internal/report_generator/helper.py
- pycaret/internal/report_generator/utils.py
- pycaret/internal/utils.py
- pycaret/nlp.py
- pycaret/regression.py
- pycaret/tests/test_report_anomaly.py
- pycaret/tests/test_report_clustering.py
- pycaret/tests/test_report_nlp.py
- requirements.txt
> Report generator

- tutorials/README.md
tutorials readme.md was empty
I have added the description of the tutorials file with thier respective links.
**![image](https://user-images.githubusercontent.com/37452506/145259273-aaa175cc-6636-466f-9498-f9073f8f0b92.png)**  | <b>![image](https://user-images.githubusercontent.com/37452506/145259170-75d59f2c-4e8c-45cc-91b6-8269bbe8217a.png) </b> |
> Tutorials readme.md updated

- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/tests/test_time_series.py
- pycaret/tests/time_series_test_utils.py
Add code that supports frequencies like '10T'. Currently it is only handling frequency that are member of the class Season_Period. 
Added code that detects frequencies that has both number and alphabets in it. Then returns the seasonal_period according to it. 
For example, 
'10T' will be returned as 10*60 = 600
> Added support for alphanumeric frequencies

- examples/README.md
readme for examples folder is empty
added all the links of notebooks in readme of example folder
**![image](https://user-images.githubusercontent.com/37452506/145790176-93c64d00-e42e-4ef2-9714-f699dad8a87b.png)**  | <b>![image](https://user-images.githubusercontent.com/37452506/145790268-ed86af98-df34-4741-bd13-6e0e2ada43a8.png) </b> |
> Readme for examples folder is added

- pycaret/internal/preprocess.py
fix a bug of hard code, that make the input parameter is useless
> fix a bug of hard code

- docs/source/contribute.rst
Totally forgot about Sphinx generated documentation when working on https://github.com/pycaret/pycaret/pull/1946. Sorry...
translated my own contribution from markdown in https://github.com/pycaret/pycaret/blob/master/CONTRIBUTING.md to RST in readthedocs Sphinx generated documentation.
> [DOC] Add contributing instructions to Sphinx generated docs

- pycaret/classification.py
- pycaret/internal/drift_report.py
- pycaret/internal/tabular.py
- pycaret/regression.py
- pycaret/tests/test_drift_report.py
- requirements-optional.txt
Added new functionality in the `predict_model` function.
Refer to this [issue](https://github.com/pycaret/pycaret/issues/1918).
> add drift_report parameter in predict_model

- pycaret/classification.py
- pycaret/internal/tabular.py
- pycaret/regression.py
> add plot_kwargs parameter and label encoder in confusion_matrix and AUC

- pycaret/internal/plots/time_series.py
`plot_time_series_decomposition` takes `sp_to_use` as `data-kwargs` to set the `period` of time -s series decomposition. 
> `sp_to_use` for time series decomposition plot.

- pycaret/classification.py
- pycaret/internal/tabular.py
- pycaret/regression.py
- pycaret/tests/test_dashboard.py
- requirements-optional.txt
```
data = get_data('iris')
s = setup(data, target = 'species', session_id = 123)
lr = create_model('lr')
dashboard(lr, display_format='inline')
```
```
data = get_data('boston')
from pycaret.regression import *
s = setup(data, target = 'medv', session_id = 123)
lr = create_model('lr')
dashboard(lr, display_format='inline')
```
> added new function dashboard in pycaret.classification and pycaret.regression

- pycaret/classification.py
- pycaret/internal/tabular.py
- pycaret/regression.py
> fix evaluate_model

- pycaret/internal/tabular.py
fixed rendering for display_format streamlit for non yellowbrick plots
> fixed rendering for display_format streamlit for non yellowbrick plots

- pycaret/classification.py
- pycaret/internal/tabular.py
- pycaret/regression.py
- pycaret/tests/test_create_docker.py
Added a new function `create_docker` that generates `requirements.txt` and `Dockerfile` file.
```
data = get_data('iris')
s = setup(data, target = 'species', session_id = 123)
lr = create_model('lr')
create_api(lr, 'my_first_api')
create_docker('my_first_api')
```
> added new function create_docker

- pycaret/internal/tabular.py
> fix issue with tsne plot in clustering when pca=True in setup #2031

- pycaret/internal/pycaret_experiment/time_series_experiment.py
#1744
Closes #1744
Passing `sp_to_use` value to the plot_ function from outside to that it can be used appropriately in the decomposition function.
Unit tests will be rerun on GitHUb
> completed fix for correct seasonal fix in decomp plots

- pycaret/anomaly.py
- pycaret/classification.py
- pycaret/clustering.py
- pycaret/internal/persistence.py
- pycaret/regression.py
- pycaret/tests/test_persistence.py
#1801 
#1801 
Added the optional path in the authentication dictionary. This fixed the issue for load_model() when using AWS with a specific path. When path is not given, the code behaves the same way as before.
- [ x] This change requires a documentation update
The test_deploy_model() function in test_persistence.py is updated to capture this issue. The test would fail without the fix.
NA
- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
- [ x] I have added …
> Added the optional path for AWS S3

- CHANGELOG.md
- pycaret/utils.py
- setup.py
- setup_nightly.py
> 2.3.6 update prep

- requirements.txt
> Remove numpy from requirements (covered by pandas)

- pycaret/classification.py
- pycaret/internal/tabular.py
- pycaret/regression.py
- pycaret/tests/test_create_app.py
- requirements-optional.txt
create a new function create_app that creates basic gradio app
available in `pycaret.classification` and `pycaret.regression`
```
data = get_data('diamond')
from pycaret.regression import *
s = setup(data, target = 'Price', silent=True)
dt = create_model('dt')
create_app(dt)
```
test case also added but commented out since this starts a localhost Flask server and GitHub actions will get stuck on this.
> create a new function create_app that creates basic gradio app

- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/tests/test_time_series_setup.py
- pycaret/time_series.py
#2033 
Closes #2033
Refactored in a more organized way
Unit tests to be rerun on GitHub
> Refactor Time Series Experiment setup method

- requirements.txt
> Pin `numba<0.55`

- pycaret/internal/tabular.py
> Replace unsupported characters in df

- pycaret/internal/pycaret_experiment/tabular_experiment.py
Closes #2068
Check added when data is too short. 
Unit tests to be rerun on GitHub.
> Fix for short time series - recommended_D test failure  closes #2068

- pycaret/internal/plots/time_series.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
#1654 
Initial attempt to add difference plots (does not include an option for ACF and PACF of differences yet).
Time Series plotting unit tests have been run locally
> Added Time Series difference plot

- pycaret/internal/plots/time_series.py
- pycaret/internal/plots/utils/time_series.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/time_series.py
Closes #1654
- Added option to show ACF and PACF along with differences
- Refactored such that Time Series, ACF, PACF, QQ, Dist etc. can be plotted in subplots using reusable code
Existing unit tests pass
```python
exp.plot_model(plot="diff", data_kwargs={"order_list": [1, 2], "pacf": True})
exp.plot_model(plot="diff", data_kwargs={"lags_list": [[1], [1, 12]], "acf": True, "pacf": True})
```
> Enhance Time Series Difference Plots - Closes #1654

- pycaret/internal/drift_report.py
> bug resolving for drift report of categorical columns

- pycaret/datasets.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/internal/pycaret_experiment/utils.py
- pycaret/internal/utils.py
- pycaret/tests/conftest.py
- pycaret/tests/test_time_series_exogenous.py
- pycaret/time_series.py
#1588 
Initial changes to support exogenous variables
Currently, only rerunning existing unit tests. Will add unit tests with exogenous variables later.
> Support for univariate forecasting with exogenous variables

- pycaret/containers/models/time_series.py
- pycaret/internal/plots/time_series.py
- pycaret/tests/conftest.py
- pycaret/tests/time_series_test_utils.py
Closes #1894 
For all time series models that handle seasonality, I make them use `sp_to_use` instead of the `seasonal_period` specified in the experiment setup. 
With this change a couple of None checks were irrelevant, so I removed them as well (indicated with comments on the PR). 
Unit tests (no new unit tests were added). 
`NA`
Not sure about this one: black pre-commit hook introduced changes in parts of the code I did not modify (in files I modify) and I ended up removing them to avoid mixing them with my changes. Should I reintroduce them in this PR?
> Time series models to use sp_to_use

- setup.py
> Solving installing UTF error

- pycaret/internal/plots/time_series.py
- pycaret/internal/plots/utils/time_series.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/time_series.py
Closes #1656
- Added plots for frequency component - periodogram and FFT
- Plots are available as individual plots or as part of "difference" diagnostics
Existing unit tests pass
```python
exp.plot_model(plot="periodogram")
exp.plot_model(plot="fft")
```
```python
exp.plot_model(plot="diff", data_kwargs={'periodogram': True})
exp.plot_model(plot="diff", data_kwargs={'fft': True})
exp.plot_model(plot="diff", data_kwargs={'acf': True, 'periodogram': True, "fft": True})
```
> Added plotting of frequency components 

- pycaret/internal/plots/time_series.py
- pycaret/internal/plots/utils/time_series.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/time_series.py
Closes #1751
Closes #2102
Closes #2155 
Implements #2153 partially
- Added ability to plot CCF plots between target and exogenous variables in time series. Can also be used for univariate modeling in which case, it plots ACF.
- Added the ability to plot exogenous variables in the default time series plot (if exogenous variables are present)
- Fixed bug where some exogenous variables were being dropped from the list.
- Disabled hovering of certain plots based on data (time series and frequency components)
Local testing is done and existing unit tests should be able to pick up the new plot type.
```python
exp.plot_model(plot="ccf", data_kwargs={"include": ["unrate", "nfjobschg"]})
```
> Plotting updates + Bug Fixes for Univariate Forecasting with exogenous variables 

- pycaret/datasets.py
Fixes #2107 
Let me know if it is alright.
> fixed value error when dataset address was given

- requirements-ts.txt
Closes #1974 
Updated sktime version which fixes this issue.
Existing unit tests should pass including `test_setup_seasonal_period_alphanumeric`
> Alphanumeric frequency support in Time Series

- pycaret/internal/plots/time_series.py
- pycaret/internal/plots/utils/time_series.py
Closes #2210 
Closes #2211
Fixed bugs for Feb release
Unit tests pass on GitHub
- [x ] My changes generate no new warnings.
> Ts fix feb

- pycaret/internal/plots/time_series.py
- pycaret/internal/plots/utils/time_series.py
Closes #2216 
Closes #2217
- Fixed hoverinfo issue in time series plots
- Enhanced "diagnostic" plots with Periodogram and PACF info
Existing unit tests to pass on GitHub
> Fix and Enhancement for Feb Time Series release

- requirements.txt
Closes #2216 
Closes #2217
- Fixed hoverinfo issue in time series plots
- Enhanced "diagnostic" plots with Periodogram and PACF info
Existing unit tests to pass on GitHub
> Time series Feb release - Fixes plus enhancements

- pycaret/containers/models/time_series.py
- pycaret/internal/plots/time_series.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/internal/pycaret_experiment/time_series_experiment.py
- pycaret/tests/conftest.py
- pycaret/tests/test_time_series_setup.py
- pycaret/tests/test_time_series_stats.py
- pycaret/tests/time_series_test_utils.py
Closes #2166
- renamed sp_to_use to primary_sp_to_use per #2166
Unit tests tested locally (partially). Should pass on GitHub.
> Rename `sp_to_use` variables

- pycaret/classification.py
- pycaret/internal/preprocess/preprocessor.py
- pycaret/internal/preprocess/transformers.py
- pycaret/regression.py
- pycaret/tests/test_preprocess.py
Added new imputation strategies.
The new options for numerical columns are:
- "drop": Drop rows containing missing values.
- "mean": Impute with mean of column.
- "median": Impute with median of column.
- "mode": Impute with most frequent value.
- "knn": Impute using a K-Nearest Neighbors approach.
- int or float: Impute with provided numerical value.
The new options for categorical columns are:
- "drop": Drop rows containing missing values.
- "mode": Impute with most frequent value.
- str: Impute with provided string.
> improved imputation strategies

- pycaret/internal/preprocess.py
> Fix spelling mistakes in function docstrings

- CHANGELOG.md
- README.md
- pycaret/utils.py
- setup.py
- setup_nightly.py
> Update version, changelog to 2.3.7

- pycaret/classification.py
- pycaret/clustering.py
- pycaret/internal/tabular.py
- pycaret/nlp.py
- pycaret/regression.py
- pycaret/tests/test_transform_target.py
Fixes an exception with `dashboard_logger`.
> Fix loggign param, add docs

- CHANGELOG.md
- README.md
- pycaret/utils.py
- setup.py
- setup_nightly.py
> Bump version to 2.3.8

- pycaret/internal/Display.py
- pycaret/internal/utils.py
- pycaret/tests/test_time_series_base.py
- pycaret/tests/test_time_series_setup.py
- pycaret/tests/time_series_test_utils.py
- pycaret/time_series/forecasting/functional.py
- pycaret/time_series/forecasting/oop.py
- pycaret/utils/time_series/forecasting/__init__.py
Closes #1893
- Refactored predict_model so it is easier to follow
- Unified handling of fh (accepts ForecastingHorizon as well) and updated docstrings
- Updated & expanded unit tests
> Refactored predict_model, unified fh handling

- pycaret/anomaly.py
- pycaret/classification.py
- pycaret/clustering.py
- pycaret/internal/tabular.py
- pycaret/nlp.py
- pycaret/regression.py
`log_experiment` can now be used to specify what loggers should be used exactly.
> Make `log_experiment` more configurable

- pycaret/anomaly.py
- pycaret/classification.py
- pycaret/clustering.py
- pycaret/internal/tabular.py
- pycaret/nlp.py
- pycaret/regression.py
> Make `WandbLogger` not mandatory

- pycaret/internal/tabular.py
> Make `return_train_score=False` return the old output format

- requirements.txt
> Refactor dependencies

- pycaret/internal/tabular.py
- requirements.txt
Closes https://github.com/pycaret/pycaret/issues/2348
> Fix `predict_model` with loaded pipeline

- .github/workflows/test.yml
- pycaret/tests/test_eda.py
- requirements.txt
> Fix dependency install in CI

- pycaret/classification/oop.py
- pycaret/datasets.py
- pycaret/internal/pycaret_experiment/unsupervised_experiment.py
- pycaret/regression/oop.py
- pycaret/time_series/forecasting/oop.py
> Use PyCaret's Display class instead of IPython

- pycaret/time_series/forecasting/functional.py
- pycaret/time_series/forecasting/oop.py
- pycaret/utils/time_series/__init__.py
Closes #1854
Support for more frequencies has been added including business week/days
Existing unit tests should automatically pick up the new frequency types.
> support for business week plus more seasonal periods per #1854

- pycaret/internal/pycaret_experiment/__init__.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/tests/test_time_series_metrics.py
- pycaret/tests/test_time_series_setup.py
- pycaret/time_series/forecasting/oop.py
- pycaret/utils/_dependencies.py
- Closes #2388 
- Closes #2386
- Closes #2390 
- Partially implements #2263
- Better error handling in the Time Series module (refer to the issues above for details)
- Better handling of optional dependency error messages.
- One unit tests added for time series
- Rest of the unit tests should pass on GitHub
> Multiple fixes

- CHANGELOG.md
- README.md
- pycaret/utils.py
- setup.py
- setup_nightly.py
> Bump version to 2.3.10

- pycaret/tests/test_time_series_plots.py
- pycaret/tests/time_series_test_utils.py
- pycaret/time_series/forecasting/functional.py
- pycaret/time_series/forecasting/oop.py
Closes #2368 
Allow users to pass custom labels when passing multiple models
> implemented changes for #2368 and added unit tests

- pycaret/internal/plots/time_series.py
- pycaret/internal/plots/utils/time_series.py
- pycaret/time_series/forecasting/functional.py
- pycaret/time_series/forecasting/oop.py
Partially implements #2364
- Support for multiple data types in plots added for 
- Correlation plots (ACF, PACF) 
- Frequency Plots (Periodogram, FFT)
- Decomp 
- Cleanup for others that do not support multiple data types in plots
- CCF
- Diagnostics
- Diff
Unit tests passed on GH
> Ts plot miss data

- pycaret/internal/plots/time_series.py
- pycaret/internal/plots/utils/time_series.py
- pycaret/time_series/forecasting/oop.py
Closes #2418 
Implemented ability to pass multiple estimators for plots such as ACF/PACF, Periodogram/FFT and Classical/STL Decomposition
Existing unit tests pass.
> implemented some plots for multiple estimators per #2418

- .github/workflows/lock_old_threads
Adds a workflow to lock issues that have been closed for more than a week, unless they have the `do not lock` label.
Closes https://github.com/pycaret/pycaret/issues/2438
> Create lock_old_threads workflow

- pycaret/containers/models/time_series.py
- pycaret/internal/ensemble.py
- pycaret/tests/test_time_series_base.py
- pycaret/tests/test_time_series_setup.py
- pycaret/tests/test_time_series_utils_forecasting.py
- pycaret/tests/test_time_series_utils_forecasting_pipeline.py
- pycaret/tests/test_time_series_utils_plots.py
- pycaret/time_series/forecasting/functional.py
- pycaret/time_series/forecasting/oop.py
- pycaret/utils/time_series/forecasting/__init__.py
- pycaret/utils/time_series/forecasting/model_selection.py
- pycaret/utils/time_series/forecasting/models.py
- pycaret/utils/time_series/forecasting/pipeline.py
- requirements.txt
Closes #2202
Closes #2065 
Closes #2482 
Closes #2459 
- Upgraded to the latest version of sktime which deprecates `return_pred_int` in `predict()` calls. Made appropriate changes per #2202 
- Also added `setup` argument for `point_alpha` (quantile to use for point prediction)
- Removed `enforce_pi` argument and used `point_alpha` to achieve functionality.
- unpins scipy with upgrade of sktime to latest version
- Updated `create_model` to include all available models. 
> Upgrade to sktime 0.11.3 + changes for prediction deprecations

- pycaret/internal/pycaret_experiment/pycaret_experiment.py
- pycaret/nlp/__init__.py
- pycaret/utils/_show_versions.py
Closes #2473 
Added option in `show_versions` to use logger instead of printing the results.
Existing unit tests to pass
> Updated logging in `show_versions`

- pycaret/internal/pycaret_experiment/pycaret_experiment.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/time_series/forecasting/oop.py
Closes #2359 
Moved checks from time series module to base classes and called from base class itself.
Unit tests to pass on GitHub
> Added setup checks in all base libraries instead of Time Series

- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/internal/utils.py
Closes #2451
Improved error message when the target is specified as part of a feature list
unit tests to pass on GitHub
```python
from pycaret.classification import ClassificationExperiment
juice = get_data("juice")
exp = ClassificationExperiment()
exp.setup(data=juice, target="Purchase", categorical_features=["Purchase"])
```
```
> Better error message

- resources/PyCaret for Machine Learning.md
Article on PyCaret for Machine Learning
> Create PyCaret for Machine Learning.md

- pycaret/anomaly/__init__.py
- pycaret/containers/models/clustering.py
- pycaret/tests/test_anomaly.py
- requirements.txt
Closes #2540 
Closes #2541 
Bug fixes for clustering and anomaly setup and imports
Tested locally and all existing unit tests to pass to GH
> Fixes clustering anomaly

- requirements.txt
Addresses #2542 for 3.0.0rc1 release but not for pycaret-ts-alpha
Updated sktime version to 0.11.4 which fixes the issue with sklearn 1.1.0
Unit tests to pass on GH
> updated requirements to fix #2542 for 3.0.0rc1 release

- pycaret/internal/plots/yellowbrick.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
> Fix plotting returns (#2547)

- pycaret/internal/pipeline.py
- pycaret/internal/preprocess/transformers.py
- pycaret/tests/test_pipeline.py
Added `feature_names_in_` property (like sklearn estimators) to ge the faeture names after fit (only when fitted on pandas objects).
> added feature_names_in

- pycaret/internal/pycaret_experiment/pycaret_experiment.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/internal/pycaret_experiment/unsupervised_experiment.py
- pycaret/tests/test_anomaly.py
- pycaret/tests/test_clustering.py
Closes #2553 
Closes #2554 
Train Test indices were not set in unsupervised experiment.
Some unused variables had to be added to maintain compatibility to Tabular Experiment.
Locally
> fix for unsupervised experiment plotting

- pycaret/classification/functional.py
- pycaret/classification/oop.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/regression/functional.py
- pycaret/regression/oop.py
Option to change the plot_pipeline fontsize
> refactor_plot_pipeline

- pycaret/internal/pipeline.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/internal/pycaret_experiment/unsupervised_experiment.py
- pycaret/internal/utils.py
- pycaret/tests/test_anomaly.py
- pycaret/tests/test_classification.py
- pycaret/tests/test_clustering.py
- pycaret/tests/test_multiclass.py
- pycaret/tests/test_regression.py
Closes https://github.com/pycaret/pycaret/issues/2567
> Fix `predict_model` without first running `setup`

- pycaret/classification/functional.py
- pycaret/regression/functional.py
> convert model doc fix

- pycaret/classification/oop.py
- pycaret/regression/oop.py
> addset docstring to oop setup for clf and reg

- pycaret/time_series/forecasting/oop.py
Partially closes #2607
Fix for index checks for missing indices during setup (time series)
Existing unit test to pass
> Time Series - fix index checks

- .github/workflows/test.yml
- setup.py
> Fix colab install

- tutorials/Portuguese/Tutorial de classificacao binaria (CLF101) - Nivel iniciante.ipynb
Add CLF101 for portuguese tutorial
Tested locally using the latest pycaret version 
NA
**![image](https://user-images.githubusercontent.com/25105861/171674317-9f0649b8-1a88-4c8f-9d9a-feb058dc2f5d.png)**  | <b>![image](https://user-images.githubusercontent.com/25105861/171674383-9fc6027b-86c4-4fc4-8401-e24a36f27237.png) </b> |
> add portuguese tutorial (CLF101)

- pycaret/containers/models/time_series.py
Closes https://github.com/pycaret/pycaret/issues/2661
CI fails due to `n_jobs` not being an attribute of ARIMA
> Remove `n_jobs` from ARIMA

- pycaret/internal/pycaret_experiment/supervised_experiment.py
Closes https://github.com/pycaret/pycaret/issues/2645
> Fix bad `choose_better` output

- .github/workflows/build_publish_nightly.yml
- .github/workflows/build_publish_stable.yml
- .github/workflows/test.yml
- pycaret/internal/plots/time_series.py
- pycaret/internal/plots/utils/time_series.py
- pycaret/time_series/forecasting/functional.py
- pycaret/time_series/forecasting/oop.py
- requirements.txt
Closes #2634 
Added:
*  the 'plotly-dash' and 'plotly-widget' to the `display_format` argument the `TSForecastingExperiment.plot_model` method. This allows to define how the plotly figures should be renderd. 
* created the new `display_format_kwargs` which are mainly used to configure how the plotly-figures should be renderd (when using 'plotly-dash'), and how many sample per trace should be shown)
I just ran the first cells of the [examples/time_series/forecasting/time_series_201](https://github.com/pycaret/pycaret/blob/master/examples/time_series/forecasting/time_series_201.ipynb) notebook and then used this cell with the various ts plot …
> [ENH] ✨ integrate plotly-resampler within time-series `plot_model`

- pycaret/classification/functional.py
- pycaret/classification/oop.py
- pycaret/regression/functional.py
- pycaret/regression/oop.py
> fold_strategy_docfix

- pycaret/internal/preprocess/preprocessor.py
Closes #2523
Added validation for the case when fold_strategy is "timeseries" or instance of `TimeSeriesSplit`.
> add validation case for timeseries split

- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/time_series/forecasting/oop.py
Closes #2703
Implements the changes to the lines suggested in #2703.
Ran function. This works.
NA
> Add verbose conditional to the print() statements. Closes #2703

- .github/workflows/test.yml
- pycaret/anomaly/functional.py
- pycaret/classification/functional.py
- pycaret/classification/oop.py
- pycaret/clustering/functional.py
- pycaret/internal/pipeline.py
- pycaret/internal/preprocess/preprocessor.py
- pycaret/internal/preprocess/transformers.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/internal/pycaret_experiment/unsupervised_experiment.py
- pycaret/regression/functional.py
- pycaret/regression/oop.py
- pycaret/tests/test_classification_engines.py
- pycaret/tests/test_pipeline.py
- pycaret/tests/test_preprocess.py
Closes #2688, #2693 and #2687
Also adds `groups` to preprocessing following v2.3.10's API.
> fixes 3 issues

- pycaret/internal/preprocess/transformers.py
Fixes #2748
Fix edge case bug with memory issues when the dataset contained columns of the form [othercolumn]_XX
> Fix edge case bug with memory issues

- pycaret/internal/pycaret_experiment/tabular_experiment.py
Closes #2696
Removed INPUT_COLS_WITHOUT_SPACES_FORMATTED  variable and replaced it with pydanticinputmodel and pydanticoutputmodel. This changes the post request from taking query parameters to requiring a body. It also adds automatic data validation for then input and output.
After cloning the develop branch I've noticed two additional bugs which didn't exists in the main branch.
1. First one being that self._ml_usecase doesn't have the same output as before which was either "classification" or "regression" depending on the usecase. Therefor had to change that to self._ml_usecase.name.lower().
2. Second one is a weird indentation that kept showing up in the fastapi script, I've had to remove the initial spacing of the query variable
Please delete options that are …
> Update `create_api` to add pydantic input and output

- requirements-optional.txt
> Pin fugue~=0.6.6

- pycaret/utils/_dependencies.py
- pycaret/utils/_show_versions.py
- requirements.txt
Improves `show_versions` and `_check_soft_dependencies` by changing the way we obtain the module versions. Previously, we had to import each dependency and obtain its version, which was not only time-consuming but also caused memory issues. Now, we obtain package metadata and get the version that way. We fall back to the old way in case there is no package metadata.
**original screenshot** …
> Improve dependency checking

- pycaret/internal/pycaret_experiment/pycaret_experiment.py
- pycaret/tests/time_series_test_utils.py
- pycaret/utils/time_series/__init__.py
- pycaret/utils/time_series/forecasting/pipeline.py
- requirements.txt
Closes #2674 
Closes #2754 
Closes #2607 (done automatically due to upgrade to sktime 0.13.0)
- Upgraded to sktime 13.0 and took care of deprecations and default argument (`Differencer`) changes in this version
- Bug fixes with pipeline getting overridden by `_get_imputed_data`
- Internal variables for transformed dataset made consistent
Unit tests pass on GitHub
> updated to sktime 13.0

- pycaret/anomaly/functional.py
- pycaret/clustering/functional.py
- pycaret/internal/pycaret_experiment/unsupervised_experiment.py
Closes #2810 
Update error and docstrings for unsupervised learning regarding iterative imputation type.
> Fix iterative imputation clustering

- requirements.txt
Closes #2771
Bug fix made in sktime 0.13.1
Unit tests to pass in GitHub
> Updated sktime to 0.13.1 to fix #2771

- .github/workflows/test.yml
- requirements.txt
Tests are failing due to the new release for pmdarima 2.0.0.
Related:  
- https://github.com/alan-turing-institute/sktime/issues/3300
- https://github.com/alan-turing-institute/sktime/pull/3301
- https://github.com/alan-turing-institute/sktime/pull/3302
Pinned pmdarima temporarily to not use 2.0.0. Will need to remove this once fixed in sktime.
Existing unit tests should pass on GitHub
> fix for failing time series tests due to pmdarima 2.0.0

- README.md
- docs/source/index.rst
Updated README file and documentation index page - fixed some broken links.
> Documentation update - fixed broken links

- Docker_files/pycaret_full/Dockerfile
- Docker_files/pycaret_slim/Dockerfile
Add docker files to the repo for clear visibility and possible community support. Flies added are stand-alone and do not interact with any existing files 
No testing required
> adding stand alone docker files for slim and full version.

- pycaret/containers/models/time_series.py
- tests/test_time_series_engines.py
Closes #2899
Added default and alternate engines for reduced regression based models.
Unit test have been updated and pass locally.
Sometimes, the execution with sklearnex gets stuck. This may need more investigation.
> Added Intel Accelarator support for Time Series

- pycaret/classification/oop.py
- pycaret/internal/preprocess/preprocessor.py
- pycaret/internal/preprocess/transformers.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/regression/oop.py
- requirements-optional.txt
- requirements.txt
- tests/test_preprocess.py
Closes #2853
Closes #2813
Closes #2757
Fixes #2872
* Fixed a bug where encoders would be added to the pipeline unnecessary
* Fixed a bug where predict_model with raw_score=True would fail
* Fixed a bug where create_app would fail when the pipelien created new columns
* Improved error message for transformers that return existing columns
* Fixed a bug where iterative imputation parameters were displayed when imputer_type=None
> fix bugs in preprocessing, predict_model and create_app

- pycaret/classification/functional.py
- pycaret/classification/oop.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/regression/functional.py
- pycaret/regression/oop.py
- pycaret/time_series/forecasting/functional.py
- pycaret/utils/generic.py
> fix create_api and wrong engine bug

- README.md
Updated details about time series
> Updates Time Series Section

- pycaret/loggers/base_logger.py
- pycaret/loggers/dashboard_logger.py
- pycaret/loggers/mlflow_logger.py
> Log experiment USI in MLFlow correctly

- pycaret/internal/plots/time_series.py
Closes #3029
Prediction intervals are now displayed correctly.
Tested locally, unit tests should pass on Github
> Fix for prediction limits (time series)

- pycaret/containers/models/time_series.py
Closes #3027
Set the logger appropriately
Unit tests to pass on GitHub
> Fixes time series setup issue on Colab

- requirements.txt
Closes #2988
Relaxed library versions to match sktime
Unit tests to pass on GitHub
> Relaxes library versions for dependencies

- pycaret/time_series/forecasting/oop.py
- tests/test_time_series_mlflow.py
Closes #1790
Added mlflow logging for EDA plots in setup
> Add mlflow EDA logging in setup

- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/utils/generic.py
Closes #3016 
Closes #3034
Closes #2960 
Fixed a bug where groups always used the complete dataset length instead of adapting to the specific data subset.
> fix groups

- pycaret/classification/oop.py
- pycaret/regression/oop.py
- pycaret/utils/generic.py
- requirements-optional.txt
Add deepchecks to dependencies. See #2882 
Pin fairlearn to version 0.7.0. Newest version can not handle metrics with `pos_label` as str, which makes the tests fail.
Fix a bug with groups. See #3071
> add deepcheks, fix groups and pin fairlearn

- pycaret/internal/pycaret_experiment/supervised_experiment.py
- tests/test_classification.py
- tests/test_multiclass.py
- tests/test_regression.py
Closes https://github.com/pycaret/pycaret/issues/2924
Fixes pop from empty list in `automl(use_holdout=True)`.
> Fix `automl` with `use_holdout` (#2924)

- pycaret/containers/models/classification.py
- pycaret/containers/models/regression.py
- pycaret/containers/models/time_series.py
- pycaret/internal/plots/time_series.py
- pycaret/internal/pycaret_experiment/pycaret_experiment.py
- pycaret/time_series/forecasting/oop.py
- pycaret/utils/_dependencies.py
- pycaret/utils/time_series/forecasting/model_selection.py
- pycaret/utils/time_series/forecasting/pipeline.py
> Update sktime links, add tuning grids for Dummy models

- pycaret/internal/pycaret_experiment/tabular_experiment.py
Check estimator’s “predict_proba” attribute for “auc” was implemented two times.
Check estimator’s “predict_proba” attribute for “auc” was implemented two times. One was deleted. 
NA
> removing extra auc plot checking

- pycaret/containers/models/time_series.py
None
Switched from using window_length feature in reduced regression model to using transformers which will provide more flexibility in the future for creating time series features.
Unit tests pass locally and should pass on GH
> Updates to Reduced Regression Models

- pycaret/internal/pycaret_experiment/pycaret_experiment.py
Closes #3116
Aligned get_config keys with the class attributes.
Unit tests to pass on GH
Original is in the #3116 
Fix is below
> Aligning `get_config` with class attributes

- .gitignore
- pycaret/utils/__init__.py
- requirements.txt
> small fixes

- pycaret/arules/__init__.py
- pycaret/nlp/__init__.py
- pycaret/utils/__init__.py
- requirements.txt
Closes #3144 
Added deprecation warning for NLP and ARules modules.
Exiting unit tests must pass
> added deprecation warnings

- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/loggers/dashboard_logger.py
Closes #3036
Removed unnecessary code
Existing unit tests to pass
> finalize model fix

- .github/workflows/test.yml
Tests are currently taking about 2 hours to run. Time the tests so we can potentially restructure them to take less time in the future.
Existing unit test to pass
> time tests to improve runtimes later

- pycaret/time_series/forecasting/oop.py
Removed the old class that had deprecation notice for a while.
Existing unit tests to pass
> removing old time series class from library

- pycaret/internal/pycaret_experiment/supervised_experiment.py
Closes https://github.com/pycaret/pycaret/issues/3166
> Close display in `get_leaderboard`

- pycaret/anomaly/functional.py
- pycaret/classification/functional.py
- pycaret/clustering/functional.py
- pycaret/internal/pycaret_experiment/pycaret_experiment.py
- pycaret/regression/functional.py
- pycaret/time_series/forecasting/functional.py
> Allow None in `get_config`

- pycaret/internal/display/display_backend.py
Closes https://github.com/pycaret/pycaret/issues/3187
Fixes jupyter notebook detection in Colab to cover a case where a python script is ran directly instead of through the notebook, which lead to an exception.
> Fix display detection on non-jupyter Colab

- pycaret/time_series/forecasting/oop.py
Closes #3212
Testes locally and existing unit tests must pass on GH
```python
import pandas as pd
data = pd.read_csv("Incident_data.csv")
data["date"] = pd.to_datetime(data["date"])
data.set_index("date", drop=True, inplace=True)
data = data.asfreq("d")
##Importing and Initializing time series module
from pycaret.time_series import *
forecast_tickets = setup(data, fold=5, fh=15, numeric_imputation_target="ffill")
plot_model(data_kwargs={"plot_data_type": ["original", "imputed"]})
```
> Fixed Time Series Plotting for some cases

- pycaret/internal/tests/time_series.py
- pycaret/time_series/forecasting/functional.py
- pycaret/time_series/forecasting/oop.py
- pycaret/utils/time_series/__init__.py
- tests/test_time_series_setup.py
Closes #3202
Added ability to select the split to be used to determine the hyperparameters
Unit test have been added and existing tests need to be updated.
> initial implementation for #3202

- .github/workflows/build_publish_nightly.yml
- .github/workflows/build_publish_stable.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/test.yml
Closes https://github.com/pycaret/pycaret/issues/3152
> Update checkout version in GH workflows

- tests/test_classification_engines.py
- tests/test_regression_engines.py
Parametrizes sklearnex engine tests and disables SVM in those due to https://github.com/intel/scikit-learn-intelex/issues/1158
> Break up skelarnex engine tests, disable SVM in CI

- pycaret/internal/pycaret_experiment/supervised_experiment.py
- tests/test_supervised_predict_model.py
Closes #3249
Placed the assignment of X_test_untransformed  and y_test_untransformed before filtering the column of the dataframe so X_test_untransformed  keep all the columns of the passed dataframe and not only the one needed for the prediction.
This works only when a dataframe is passed as an argument in predict_model(). I am not familiar enough with the code to make the change when no data is provided (but I might not be needed).
Unit test have been added in tests/test_supervised_predict_model.py to ensure the columns of the raw dataframe are contained in the returned dataframe.
**original screenshot** …
> Fix/return all cols in predict_model()

- pycaret/classification/oop.py
- pycaret/internal/pycaret_experiment/non_ts_supervised_experiment.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/internal/pycaret_experiment/ts_supervised_experiment.py
- pycaret/regression/oop.py
- pycaret/time_series/forecasting/oop.py
#3183
#3237 
- Isolates some of the class properties into their respective classes
- Also, initial attempt to clean out switches in the `_TabularExperiment` methods like `create_model` but more work is needed here.
- This is in prep for the addition of the Time Series Clustering Module per #3237 
Existing unit tests should pass
> initial class isolation

- .github/workflows/test.yml
- pycaret/__init__.py
- pycaret/arules/__init__.py
- pycaret/classification/functional.py
- pycaret/classification/oop.py
- pycaret/internal/cloudpickle_compat.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/loggers/mlflow_logger.py
- pycaret/nlp/__init__.py
- pycaret/parallel/fugue_backend.py
- pycaret/utils/__init__.py
- requirements-optional.txt
- requirements-test.txt
- requirements.txt
- tests/conftest.py
> Optimize threshold improvement

- .github/workflows/test.yml
- pycaret/parallel/fugue_backend.py
- requirements-optional.txt
- requirements-test.txt
This PR upgrades Fugue and resolves building issues
* Upgrade Fugue to 0.8.0
* Modify the code for a breaking change on the Fugue side
The existing tests should still work without change
NA
> Upgrade Fugue to 0.8.0

- pycaret/classification/__init__.py
- pycaret/classification/functional.py
- pycaret/classification/oop.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/regression/__init__.py
- pycaret/regression/functional.py
- pycaret/regression/oop.py
- tests/test_check_drift.py
- tests/test_drift_report.py
Closes https://github.com/pycaret/pycaret/issues/3190
> Drift report rework

- pycaret/internal/display/display_backend.py
- pycaret/internal/display/progress_bar.py
- pycaret/internal/logging.py
- pycaret/internal/preprocess/time_series/forecasting/preprocessor.py
- pycaret/utils/time_series/__init__.py
Signed-off-by: Daiki Katsuragawa <50144563+daikikatsuragawa@users.noreply.github.com>
I found some incompatible types when I checked the type hints. This PR is a fix for them.
> Fix incompatible types

- .github/workflows/test.yml
> Pin black, isort, flake8 versions in CI

- pycaret/internal/pycaret_experiment/pycaret_experiment.py
- pycaret/internal/tests/stats.py
- pycaret/internal/tests/time_series.py
- pycaret/loggers/base_logger.py
- pycaret/utils/datetime.py
The code has been modified (refactored) based on `mypy`'s suggestions.
```sh
mypy --ignore-missing-imports pycaret/
```
*Not all
> Fix errors detected by mypy

- pycaret/utils/time_series/forecasting/model_selection.py
Closes #3333
Changes in sktime 0.16.0 caused breaking changes to cutoff. See #3333 for details and suggested fix by sktime.
Tested locally plus existing tests should pass on GitHub
> Time Series Cutoff presentation fix

- pycaret/time_series/forecasting/functional.py
- pycaret/time_series/forecasting/oop.py
- tests/test_time_series_setup.py
Closes #3308
Implements option to force use a seasonal period value (i.e. ignore seasonality test)
Unit test have been added
> Added option to force usage of a seasonal period

- tutorials/README.md
A simple modification to update the README.md page in tutorial folder to fix existing broken link and remove tutorial with no notebook found
- [ x] Bug fix (non-breaking change which fixes an issue)
Recheck the updated link leads to the notebook page instead of 404 not found page
NA
> Update broken link

- .github/workflows/test.yml
- requirements.txt
> Pin plotly-resampler>=0.8.3.1

- pycaret/containers/metrics/classification.py
- pycaret/internal/metrics.py
Ensures that ROC-AUC metric uses default values for binary classification (this should have been the behavior previously, according to sklearn docs, but we add an extra layer of security here).
> Ensure that binary metric arguments are correct

- pycaret/internal/memory.py
Sets the upper limit of joblib cache folder at 10 GB. This will be enforced every 20 calls to `cache` (this is a somewhat expensive operation).
> Set upper limit of joblib memory at 10GB

- pycaret/internal/memory.py
- tests/test_memory.py
Closes https://github.com/pycaret/pycaret/issues/3384
Fixes joblib bug to allow classes defined in `__main__` to be hashed.
Note that this issue will still happen if the class is defined inside a function. We'll need to use cloudpickle for that (left as TODO).
> Fix hashing of custom classes

- requirements-optional.txt
Closes https://github.com/pycaret/pycaret/issues/3385
Ray wheels are now provided for Windows
> Install Ray on Windows

- pycaret/internal/pipeline.py
- pycaret/internal/preprocess/transformers.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/utils/generic.py
- tests/test_regression.py
Closes https://github.com/pycaret/pycaret/issues/3377
Honestly we should really clean up `predict_model` at some point!
> Fix `predict_model` with target transformation

- README.md
Added and organized badges (similar to sktime). Looks something like this now...
> Added and organized badges

- pycaret/internal/preprocess/preprocessor.py
- tests/test_preprocess.py
> add duplicate indices check

- pycaret/time_series/forecasting/oop.py
- pycaret/utils/time_series/__init__.py
- tests/test_time_series_utils.py
The solution indicated here: https://github.com/pycaret/pycaret/issues/3417#issuecomment-1476394446 required cleaning the index outside of pycaret. This utility helps automate some of this process.
Added utility function to do the cleaning.
Unit tests have been added
> added index cleaning utility for time series

- pycaret/containers/models/classification.py
- pycaret/containers/models/regression.py
Related to Issue https://github.com/pycaret/pycaret/issues/3457
Fixed distribution of [\pycaret\containers\models\regression.py] in CatBoostRegressorContainer when GPU is used.
> fix of CatboostRegresser on GPU with distribution.

- .github/workflows/test.yml
- requirements-test.txt
- requirements.txt
Temporary fix for https://github.com/sktime/sktime/issues/4468
Pinned upper limit for sktime
Existing test to pass
> pinned sktime until issue is fixed

- tests/test_classification_parallel.py
- tests/test_memory.py
- tests/test_regression_parallel.py
- tests/test_time_series_parallel.py
Disabling tests that are failing on GitHub CI (but passing locally). Not sure what the issue is yet, but since it is holding up all PRs, we decided to disable these temporarily until a fix can be found.
Failing tests: https://github.com/pycaret/pycaret/actions/runs/4750735691/jobs/8439195906
Disabled failing tests
> disabling failing tests for now.

- pycaret/containers/models/time_series.py
- pycaret/time_series/forecasting/functional.py
- pycaret/time_series/forecasting/oop.py
Closes #3475
Added STLForecaster
Unit tests should update automatically to pick up the STLFForecaster
> added STLForecaster

- pycaret/containers/models/time_series.py
- pycaret/time_series/forecasting/functional.py
- pycaret/time_series/forecasting/oop.py
Closes #3232
Closes #3234
- Added dynamic checking of seasonality type in setup.
- Removed LAR and PAR since they were not giving good results and we have many other alternatives.
Existing unit tests should pass
> Added dynamic seasonal type detection and removed bad models

- pycaret/internal/pycaret_experiment/tabular_experiment.py
- requirements.txt
Closes #3486
Pins `schemdraw` to 0.15 since 0.16 requires Python >=3.8
> update to new schemdraw

- pycaret/containers/models/time_series.py
- pycaret/internal/pycaret_experiment/pycaret_experiment.py
- requirements.txt
- Issue is with TBATS package and has been reported here: https://github.com/intive-DataScience/tbats/issues/40
- Closes #3233
- Closes #3483 
- Updated version of TBATS that fixes this - based on https://github.com/intive-DataScience/tbats/issues/40
Locally tested, GitHub regression tests should pass
> Fix for TBATS issues on M3 dataset

- pycaret/internal/preprocess/preprocessor.py
- tests/test_preprocess.py
Closes #3482
Raises an error when a dataset is provided with duplicate column names
> Check duplicate cols

- pycaret/internal/plots/utils/time_series.py
- pycaret/time_series/forecasting/oop.py
- requirements.txt
- tests/test_time_series_setup.py
* Enhances the implementation requested in https://github.com/pycaret/pycaret/issues/3232
* Relaxes some requirements for and related to sktime
* Seasonal type detection is now based on FPP https://otexts.com/fpp2/seasonal-strength.html
* Additive Strength is based on the formulae in the book
* Multiplicative Strength is a variant of the same formulae.
* TODO: Need to see how good this method is. It does not always give the best result, but may still be better than what we have right now.
> Enhanced seasonality type detection

- requirements-optional.txt
> Pin `holoviews<=1.14.9` in requirements-optional

- .github/workflows/test.yml
- pycaret/loggers/mlflow_logger.py
- pycaret/parallel/fugue_backend.py
- tests/test_classification_parallel.py
- tests/test_memory.py
- tests/test_regression_parallel.py
- tests/test_time_series_parallel.py
Unit tests are failing:
https://github.com/pycaret/pycaret/actions/runs/4750735691/jobs/8439195906
I made the change to backend serialization to make it safe for multiple serialization and deserializations.
The old tests work
NA
> Fix fugue tests

- pycaret/internal/pycaret_experiment/supervised_experiment.py
- tests/test_supervised_predict_model.py
Closes https://github.com/pycaret/pycaret/issues/3447
> Fix `predict_model` with `transform_target`

- pycaret/loggers/base_logger.py
- pycaret/loggers/comet_logger.py
- pycaret/loggers/mlflow_logger.py
- pycaret/loggers/wandb_logger.py
Closes https://github.com/pycaret/pycaret/issues/3496
> Ensure `finalize_model` logs correct pipeline

- pycaret/internal/pycaret_experiment/tabular_experiment.py
Closes https://github.com/pycaret/pycaret/issues/3444
Fixes tree plot when no label encoder is used
> Fix tree plot with no label encoder

- pycaret/time_series/forecasting/functional.py
- pycaret/time_series/forecasting/oop.py
- tests/test_time_series_setup.py
- tests/time_series_test_utils.py
Closes #3232
- Provided option for users to select seasonality type
- Reverted back default seasonality type to multiplicative (prior status quo)
Unit tests have been added and updated.
> provided option for users to provide seasonality type

- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/utils/generic.py
- tests/test_supervised_predict_model.py
Fixes metrics being returned as 0 in classification `predict_model`.
> Fix metrics being zero in `predict_model`

- pycaret/internal/persistence.py
Closes https://github.com/pycaret/pycaret/issues/3433
Removes unnecessary `deepcopy` in `save_model` which for some reason have caused issues with catboost. There should be no downside to this change.
> Fix `save_model` with catboost

- pycaret/anomaly/functional.py
- pycaret/classification/functional.py
- pycaret/classification/oop.py
- pycaret/clustering/functional.py
- pycaret/containers/metrics/anomaly.py
- pycaret/containers/metrics/classification.py
- pycaret/containers/metrics/clustering.py
- pycaret/containers/metrics/regression.py
- pycaret/containers/metrics/time_series.py
- pycaret/containers/models/anomaly.py
- pycaret/containers/models/classification.py
- pycaret/containers/models/clustering.py
- pycaret/containers/models/regression.py
- pycaret/containers/models/time_series.py
- pycaret/datasets.py
- pycaret/internal/cuml_wrappers.py
- pycaret/internal/persistence.py
- pycaret/internal/pipeline.py
- pycaret/internal/plots/time_series.py
- pycaret/internal/preprocess/iterative_imputer.py
- pycaret/internal/preprocess/preprocessor.py
- pycaret/internal/pycaret_experiment/pycaret_experiment.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/regression/functional.py
- pycaret/regression/oop.py
- pycaret/utils/generic.py
Closes #3507
Change the default encoder for high cardinality features from LeaveOneOut to TargetEncoder
> Remove leaveoneout

- pycaret/loggers/base_logger.py
- pycaret/loggers/dashboard_logger.py
- pycaret/loggers/mlflow_logger.py
- pycaret/utils/generic.py
> Fix MLflow nesting and model artifacts

- requirements-optional.txt
> Unpin holoviews

- pycaret/internal/pycaret_experiment/tabular_experiment.py
> Remove deprecated matplotlib parameter

- pycaret/loggers/base_logger.py
- pycaret/loggers/comet_logger.py
Closes https://github.com/pycaret/pycaret/issues/3572
> Fix missing `USI` argument in CometLogger

- requirements-optional.txt
Closes https://github.com/pycaret/pycaret/issues/3563
> Pin catboost<1.2 on Mac

- pycaret/internal/plots/utils/time_series.py
- pycaret/time_series/forecasting/oop.py
- tests/test_time_series_plots.py
Fixes #3565 
Unit tests has been added
> Fixes TS Plotting Issue

- pycaret/anomaly/oop.py
- pycaret/classification/functional.py
- pycaret/classification/oop.py
- pycaret/clustering/oop.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
- pycaret/internal/pycaret_experiment/unsupervised_experiment.py
- pycaret/regression/functional.py
- pycaret/regression/oop.py
- tests/test_classification_plots.py
- tests/test_regression_plots.py
This argument was always a noop.
Closes https://github.com/pycaret/pycaret/issues/3583
> Remove `use_train_data` from `plot_model`

- pycaret/internal/pycaret_experiment/supervised_experiment.py
Closes https://github.com/pycaret/pycaret/issues/3568
> Fix bad label dtype in clf `predict_model`

- pycaret/internal/preprocess/transformers.py
- tests/test_preprocess.py
Closes https://github.com/pycaret/pycaret/issues/3616
> Fix column reorder causing duplicate columns

- pycaret/containers/models/anomaly.py
- pycaret/internal/patches/pyod.py
- pycaret/internal/pycaret_experiment/unsupervised_experiment.py
- tests/test_anomaly.py
Closes https://github.com/pycaret/pycaret/issues/3606
> Force np.float64 for CBLOF

- docs/source/conf.py
- pycaret/__init__.py
- pycaret/anomaly/oop.py
- pycaret/classification/oop.py
- pycaret/clustering/oop.py
- pycaret/containers/metrics/__init__.py
- pycaret/containers/models/__init__.py
- pycaret/internal/persistence.py
- pycaret/internal/preprocess/preprocessor.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/internal/pycaret_experiment/unsupervised_experiment.py
- pycaret/regression/oop.py
- pycaret/time_series/forecasting/oop.py
- pycaret/utils/generic.py
- requirements.txt
- setup.py
- tests/conftest.py
- tests/time_series_test_utils.py
> Pin sklearn<1.3.0, bump version to 3.0.4, cleanup

- .github/workflows/test.yml
- setup.py
Removed support for python 3.7
> removed support for python 3.7

- pycaret/classification/oop.py
- pycaret/internal/preprocess/preprocessor.py
- pycaret/regression/oop.py
Closes https://github.com/pycaret/pycaret/issues/3631
> Validate `data_split_shuffle` for `timeseries` CV

- pycaret/containers/metrics/classification.py
- pycaret/internal/metrics.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- tests/test_classification.py
Closes https://github.com/pycaret/pycaret/issues/3491 
> Fix classification custom metric label encoding

- pycaret/internal/preprocess/iterative_imputer.py
- tests/test_preprocess.py
Closes https://github.com/pycaret/pycaret/issues/3636
> Fix iterative imputer with many categories

- pycaret/internal/pipeline.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
- pycaret/internal/pycaret_experiment/tabular_experiment.py
- tests/test_persistence_experiment.py
Closes https://github.com/pycaret/pycaret/issues/3594 https://github.com/pycaret/pycaret/issues/3691
> Strip pipeline in `tune_model`, fix memory pickling

- docs/source/installation.rst
N/A
As of `lightgbm>=4.0.0` ([released July 13, 2023](https://pypi.org/project/lightgbm/#history)):
* Linux and Windows Python wheels come with OpenCL-based GPU support precompiled (see e.g. https://github.com/microsoft/LightGBM/pull/5252)
* `pip install lightgbm` with option `--install-option` no longer works (see e.g. https://github.com/microsoft/LightGBM/issues/6035#issuecomment-1676415781)
This PR proposes updating the installation docs to work with `lightgbm>=4.0.0`.
1. Created a new notebook at https://colab.research.google.com/
2. attached a T4 GPU with `Edit -> Notebook Settings`
3. ran the following in a cell
```shell
!mkdir -p /etc/OpenCL/vendors && echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd
```
4. ran the following in a cell
```python
import lightgbm as lgb …
```
> [docs] update LightGBM GPU installation docs

- requirements-optional.txt
Fixes CI, see https://stackoverflow.com/questions/77213053/importerror-cannot-import-name-url-quote-from-werkzeug-urls
> Pin Werkzeug>=2.2,<3.0 to fix Flask

- README.md
No longer support python 3.7 as mentioned in change log
README.md update.
As mentioned in release change log, python 3.7 is no longer supported.
NA
> Doc(Update version): No longer support python 3.7

- pycaret/internal/patches/sklearn.py
- pycaret/internal/pipeline.py
- pycaret/internal/pycaret_experiment/supervised_experiment.py
Closes https://github.com/pycaret/pycaret/issues/3758
> Fix target transformation metrics

- pycaret/regression/oop.py
> [BUG]: default value for `optimize` in `automl()` in regression modules has to be changed

- pycaret/internal/pycaret_experiment/tabular_experiment.py
> (#3796) fix index reference in API creation

- pycaret/internal/preprocess/preprocessor.py
Closes #3846
Categorical features with 2 unique values are no longer assigned to ordinal, while they still use the Ordinal encoder.
> fix moving categorical with 2 unique values to ordinal

- pycaret/internal/pycaret_experiment/tabular_experiment.py
When running the generated API on docker would throw this exception:
`pydantic.errors.PydanticUserError: A non-annotated attribute was detected`
And also, I wasn't able to access the API running on docker.
Did not found any open issue on this problems, I found the problems when I was using pycaret.
I changed only `pycaret\internal\pycaret_experiment\tabular_experiment.py`.
There was 4 modifications:
* I added an empty line at the end of the generated Dockerfile and requirements.txt, for good practices;
* Added `pydantic==1.10.0` requirement at generated requirement.txt.
It was necessary because airflow version it's compatible with pydantic version 1.10. If you don't specify the version it will use pydantic version < 2.0.
You could also solve that error without specifying pydantic version …
> Fix create_docker()

- pycaret/classification/functional.py
- pycaret/regression/functional.py
> (#3870) align default value for `restack` in `stack_models`

- pycaret/containers/metrics/classification.py
- pycaret/internal/metrics.py
After upgrade to scikit-learn 1.4 AUC metrics crashed...
Closes: #3916
Closes: #3922
> Fix AUC metrics

- requirements-optional.txt
- tests/test_classification_engines.py
Closes https://github.com/pycaret/pycaret/issues/3964 https://github.com/pycaret/pycaret/issues/3966 https://github.com/pycaret/pycaret/issues/3959
Fixes recent CI failures by relaxing test and pinning shap~=0.44.0
> Fix sklearnex, shap and dask CI

- requirements-optional.txt
`pyyaml` version fix prevents `pycaret[full]` to be installed. Would be great if somebody could add an install test for CI/CD or to just run `pip install -e .[full]` and check the output.
Closes https://github.com/pycaret/pycaret/issues/3970
Removed `pyyaml` version fixation in `requirements-optional.txt`
Local install for python 3.10, 3.11, doesn't work for 3.12.
```
git clone git@github.com:pycaret/pycaret.git
cd pycaret
mamba create -n test python=3.10 # works also for 3.11, doesn't work for 3.12
mamba activate test
pip install .[full]
```
`NA`
**original screenshot**  | …
> Fix `pycaret[full]` cannot be installed

- pycaret/loggers/mlflow_logger.py
a problem with mlflow is affecting all tests from other pr's.
This fix allows you to unlock all other affected prs
> fix mlflow tests
